# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


add_library(lib_tint_lang_core_ir_transform STATIC
  add_empty_entry_point.cc
  add_empty_entry_point.h
  block_decorated_structs.cc
  block_decorated_structs.h
  builtin_polyfill_spirv.cc
  builtin_polyfill_spirv.h
  demote_to_helper.cc
  demote_to_helper.h
  expand_implicit_splats.cc
  expand_implicit_splats.h
  handle_matrix_arithmetic.cc
  handle_matrix_arithmetic.h
  merge_return.cc
  merge_return.h
  shader_io.cc
  shader_io.h
  shader_io_spirv.cc
  shader_io_spirv.h
  std140.cc
  std140.h
  transform.cc
  transform.h
  var_for_dynamic_index.cc
  var_for_dynamic_index.h
)

target_link_libraries(lib_tint_lang_core_ir_transform
  lib_tint_lang_core_builtin
  lib_tint_lang_core_ir
  lib_tint_lang_core_type
  lib_tint_utils_containers
  lib_tint_utils_ice
  lib_tint_utils_rtti
)

add_library(tint_lang_core_ir_transform:test STATIC
  add_empty_entry_point_test.cc
  block_decorated_structs_test.cc
  builtin_polyfill_spirv_test.cc
  demote_to_helper_test.cc
  expand_implicit_splats_test.cc
  handle_matrix_arithmetic_test.cc
  helper_test.h
  merge_return_test.cc
  shader_io_spirv_test.cc
  std140_test.cc
  var_for_dynamic_index_test.cc
)

target_link_libraries(tint_lang_core_ir_transform:test
  lib_tint_lang_core_ir
  lib_tint_lang_core_ir_transform
  lib_tint_lang_core_type
)

