# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


add_library(lib_tint_lang_core_ir_transform STATIC
  "lang/core/ir/transform/add_empty_entry_point.cc"
  "lang/core/ir/transform/add_empty_entry_point.h"
  "lang/core/ir/transform/block_decorated_structs.cc"
  "lang/core/ir/transform/block_decorated_structs.h"
  "lang/core/ir/transform/builtin_polyfill_spirv.cc"
  "lang/core/ir/transform/builtin_polyfill_spirv.h"
  "lang/core/ir/transform/demote_to_helper.cc"
  "lang/core/ir/transform/demote_to_helper.h"
  "lang/core/ir/transform/expand_implicit_splats.cc"
  "lang/core/ir/transform/expand_implicit_splats.h"
  "lang/core/ir/transform/handle_matrix_arithmetic.cc"
  "lang/core/ir/transform/handle_matrix_arithmetic.h"
  "lang/core/ir/transform/merge_return.cc"
  "lang/core/ir/transform/merge_return.h"
  "lang/core/ir/transform/shader_io.cc"
  "lang/core/ir/transform/shader_io.h"
  "lang/core/ir/transform/shader_io_spirv.cc"
  "lang/core/ir/transform/shader_io_spirv.h"
  "lang/core/ir/transform/std140.cc"
  "lang/core/ir/transform/std140.h"
  "lang/core/ir/transform/transform.cc"
  "lang/core/ir/transform/transform.h"
  "lang/core/ir/transform/var_for_dynamic_index.cc"
  "lang/core/ir/transform/var_for_dynamic_index.h"
)

target_link_libraries(lib_tint_lang_core_ir_transform
  lib_tint_lang_core_builtin
  lib_tint_lang_core_ir
  lib_tint_lang_core_type
  lib_tint_utils_containers
  lib_tint_utils_ice
  lib_tint_utils_rtti
)

tint_default_compile_options(lib_tint_lang_core_ir_transform)

add_library(tint_lang_core_ir_transform_test STATIC
  "lang/core/ir/transform/add_empty_entry_point_test.cc"
  "lang/core/ir/transform/block_decorated_structs_test.cc"
  "lang/core/ir/transform/builtin_polyfill_spirv_test.cc"
  "lang/core/ir/transform/demote_to_helper_test.cc"
  "lang/core/ir/transform/expand_implicit_splats_test.cc"
  "lang/core/ir/transform/handle_matrix_arithmetic_test.cc"
  "lang/core/ir/transform/helper_test.h"
  "lang/core/ir/transform/merge_return_test.cc"
  "lang/core/ir/transform/shader_io_spirv_test.cc"
  "lang/core/ir/transform/std140_test.cc"
  "lang/core/ir/transform/var_for_dynamic_index_test.cc"
)

target_link_libraries(tint_lang_core_ir_transform_test
  lib_tint_lang_core_ir
  lib_tint_lang_core_ir_transform
  lib_tint_lang_core_type
)

tint_default_compile_options(tint_lang_core_ir_transform_test)

