# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################

include(lang/hlsl/writer/ast_printer/BUILD.cmake)
include(lang/hlsl/writer/common/BUILD.cmake)

tint_add_library(tint_lang_hlsl_writer
  "lang/hlsl/writer/result.cc"
  "lang/hlsl/writer/result.h"
  "lang/hlsl/writer/writer.cc"
  "lang/hlsl/writer/writer.h"
)

tint_target_link_tint_libraries(tint_lang_hlsl_writer
  tint_lang_hlsl_writer_ast_printer
  tint_lang_hlsl_writer_common
  tint_lang_wgsl_ast
)

tint_target_sources(tint_benchmark
  "lang/hlsl/writer/writer_bench.cc"
)

tint_target_link_tint_libraries(tint_benchmark
  tint_bench
)

