# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


tint_add_library(tint_utils_diagnostic
  "utils/diagnostic/diagnostic.cc"
  "utils/diagnostic/diagnostic.h"
  "utils/diagnostic/formatter.cc"
  "utils/diagnostic/formatter.h"
  "utils/diagnostic/printer.cc"
  "utils/diagnostic/printer.h"
  "utils/diagnostic/source.cc"
  "utils/diagnostic/source.h"
)
if ((NOT IS_LINUX)  AND  (NOT IS_MAC)  AND  (NOT IS_WIN))
  tint_target_sources(tint_utils_diagnostic PRIVATE
    "utils/diagnostic/printer_other.cc"
  )
endif()
if (IS_LINUX  OR  IS_MAC)
  tint_target_sources(tint_utils_diagnostic PRIVATE
    "utils/diagnostic/printer_posix.cc"
  )
endif()
if (IS_WIN)
  tint_target_sources(tint_utils_diagnostic PRIVATE
    "utils/diagnostic/printer_windows.cc"
  )
endif()

tint_target_link_tint_libraries(tint_utils_diagnostic
  tint_utils_text
  tint_utils_traits
)

tint_target_sources(tint_unittests
  "utils/diagnostic/diagnostic_test.cc"
  "utils/diagnostic/formatter_test.cc"
  "utils/diagnostic/printer_test.cc"
  "utils/diagnostic/source_test.cc"
)

tint_target_link_tint_libraries(tint_unittests
  tint_utils_diagnostic
)

