# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


add_library(lib_tint_lang_spirv_reader_ast_parser STATIC
  ast_parser.cc
  ast_parser.h
  attributes.h
  construct.cc
  construct.h
  entry_point_info.cc
  entry_point_info.h
  enum_converter.cc
  enum_converter.h
  fail_stream.h
  function.cc
  function.h
  namer.cc
  namer.h
  parse.cc
  parse.h
  type.cc
  type.h
  usage.cc
  usage.h
)

target_link_libraries(lib_tint_lang_spirv_reader_ast_parser
  lib_tint_lang_core_builtin
  lib_tint_lang_core_type
  lib_tint_lang_spirv_reader_common
  lib_tint_lang_wgsl_ast
  lib_tint_lang_wgsl_ast_transform
  lib_tint_lang_wgsl_program
  lib_tint_lang_wgsl_resolver
  lib_tint_utils_containers
  lib_tint_utils_ice
  lib_tint_utils_macros
  lib_tint_utils_math
  lib_tint_utils_memory
  lib_tint_utils_rtti
  lib_tint_utils_symbol
  lib_tint_utils_text
  lib_tint_utils_traits
)

add_library(tint_lang_spirv_reader_ast_parser:test STATIC
  ast_parser_test.cc
  barrier_test.cc
  constant_test.cc
  convert_member_decoration_test.cc
  convert_type_test.cc
  enum_converter_test.cc
  fail_stream_test.cc
  function_arithmetic_test.cc
  function_bit_test.cc
  function_call_test.cc
  function_cfg_test.cc
  function_composite_test.cc
  function_conversion_test.cc
  function_decl_test.cc
  function_glsl_std_450_test.cc
  function_logical_test.cc
  function_memory_test.cc
  function_misc_test.cc
  function_var_test.cc
  get_decorations_test.cc
  handle_test.cc
  helper_test.cc
  helper_test.h
  import_test.cc
  module_function_decl_test.cc
  module_var_test.cc
  named_types_test.cc
  namer_test.cc
  parser_test.cc
  spirv_tools_helpers_test.cc
  spirv_tools_helpers_test.h
  type_test.cc
  usage_test.cc
  user_name_test.cc
)

target_link_libraries(tint_lang_spirv_reader_ast_parser:test
  lib_tint_lang_core_builtin
  lib_tint_lang_core_type
  lib_tint_lang_spirv_reader_ast_parser
  lib_tint_lang_wgsl_ast
  lib_tint_lang_wgsl_sem
  lib_tint_lang_wgsl_writer_ast_printer
  lib_tint_utils_macros
  lib_tint_utils_rtti
  lib_tint_utils_text
)

