# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


add_library(lib_tint_lang_wgsl_helpers STATIC
  append_vector.cc
  append_vector.h
  check_supported_extensions.cc
  check_supported_extensions.h
  flatten_bindings.cc
  flatten_bindings.h
)

target_link_libraries(lib_tint_lang_wgsl_helpers
  lib_tint_lang_core_builtin
  lib_tint_lang_wgsl_ast
  lib_tint_lang_wgsl_ast_transform
  lib_tint_lang_wgsl_inspector
  lib_tint_lang_wgsl_program
  lib_tint_lang_wgsl_sem
  lib_tint_utils_containers
  lib_tint_utils_diagnostic
  lib_tint_utils_rtti
  lib_tint_utils_text
)

add_library(tint_lang_wgsl_helpers:test STATIC
  append_vector_test.cc
  check_supported_extensions_test.cc
  flatten_bindings_test.cc
  ir_program_test.h
)

target_link_libraries(tint_lang_wgsl_helpers:test
  lib_tint_lang_core_builtin
  lib_tint_lang_core_ir
  lib_tint_lang_core_type
  tint_lang_wgsl_ast:test
  lib_tint_lang_wgsl_helpers
  lib_tint_lang_wgsl_program
  lib_tint_lang_wgsl_reader
  lib_tint_lang_wgsl_reader_program_to_ir
  lib_tint_lang_wgsl_resolver
  lib_tint_lang_wgsl_sem
  lib_tint_utils_text
)

