# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


add_library(lib_tint_lang_wgsl_reader_parser STATIC
  "lang/wgsl/reader/parser/classify_template_args.cc"
  "lang/wgsl/reader/parser/classify_template_args.h"
  "lang/wgsl/reader/parser/detail.h"
  "lang/wgsl/reader/parser/lexer.cc"
  "lang/wgsl/reader/parser/lexer.h"
  "lang/wgsl/reader/parser/parser.cc"
  "lang/wgsl/reader/parser/parser.h"
  "lang/wgsl/reader/parser/token.cc"
  "lang/wgsl/reader/parser/token.h"
)

target_link_libraries(lib_tint_lang_wgsl_reader_parser
  lib_tint_lang_core_builtin
  lib_tint_lang_core_type
  lib_tint_lang_wgsl_ast
  lib_tint_lang_wgsl_program
  lib_tint_lang_wgsl_resolver
  lib_tint_utils_containers
  lib_tint_utils_diagnostic
  lib_tint_utils_ice
  lib_tint_utils_macros
  lib_tint_utils_strconv
  lib_tint_utils_text
)

tint_default_compile_options(lib_tint_lang_wgsl_reader_parser)

target_sources(tint_unittests PRIVATE
  "lang/wgsl/reader/parser/additive_expression_test.cc"
  "lang/wgsl/reader/parser/argument_expression_list_test.cc"
  "lang/wgsl/reader/parser/assignment_stmt_test.cc"
  "lang/wgsl/reader/parser/bitwise_expression_test.cc"
  "lang/wgsl/reader/parser/break_stmt_test.cc"
  "lang/wgsl/reader/parser/bug_cases_test.cc"
  "lang/wgsl/reader/parser/call_stmt_test.cc"
  "lang/wgsl/reader/parser/classify_template_args_test.cc"
  "lang/wgsl/reader/parser/compound_stmt_test.cc"
  "lang/wgsl/reader/parser/const_literal_test.cc"
  "lang/wgsl/reader/parser/continue_stmt_test.cc"
  "lang/wgsl/reader/parser/continuing_stmt_test.cc"
  "lang/wgsl/reader/parser/core_lhs_expression_test.cc"
  "lang/wgsl/reader/parser/diagnostic_attribute_test.cc"
  "lang/wgsl/reader/parser/diagnostic_control_test.cc"
  "lang/wgsl/reader/parser/diagnostic_directive_test.cc"
  "lang/wgsl/reader/parser/enable_directive_test.cc"
  "lang/wgsl/reader/parser/error_msg_test.cc"
  "lang/wgsl/reader/parser/error_resync_test.cc"
  "lang/wgsl/reader/parser/expression_test.cc"
  "lang/wgsl/reader/parser/for_stmt_test.cc"
  "lang/wgsl/reader/parser/function_attribute_list_test.cc"
  "lang/wgsl/reader/parser/function_attribute_test.cc"
  "lang/wgsl/reader/parser/function_decl_test.cc"
  "lang/wgsl/reader/parser/function_header_test.cc"
  "lang/wgsl/reader/parser/global_constant_decl_test.cc"
  "lang/wgsl/reader/parser/global_decl_test.cc"
  "lang/wgsl/reader/parser/global_variable_decl_test.cc"
  "lang/wgsl/reader/parser/helper_test.cc"
  "lang/wgsl/reader/parser/helper_test.h"
  "lang/wgsl/reader/parser/if_stmt_test.cc"
  "lang/wgsl/reader/parser/increment_decrement_stmt_test.cc"
  "lang/wgsl/reader/parser/lexer_test.cc"
  "lang/wgsl/reader/parser/lhs_expression_test.cc"
  "lang/wgsl/reader/parser/loop_stmt_test.cc"
  "lang/wgsl/reader/parser/math_expression_test.cc"
  "lang/wgsl/reader/parser/multiplicative_expression_test.cc"
  "lang/wgsl/reader/parser/param_list_test.cc"
  "lang/wgsl/reader/parser/paren_expression_test.cc"
  "lang/wgsl/reader/parser/parser_test.cc"
  "lang/wgsl/reader/parser/primary_expression_test.cc"
  "lang/wgsl/reader/parser/relational_expression_test.cc"
  "lang/wgsl/reader/parser/require_directive_test.cc"
  "lang/wgsl/reader/parser/reserved_keyword_test.cc"
  "lang/wgsl/reader/parser/shift_expression_test.cc"
  "lang/wgsl/reader/parser/singular_expression_test.cc"
  "lang/wgsl/reader/parser/statement_test.cc"
  "lang/wgsl/reader/parser/statements_test.cc"
  "lang/wgsl/reader/parser/struct_attribute_decl_test.cc"
  "lang/wgsl/reader/parser/struct_body_decl_test.cc"
  "lang/wgsl/reader/parser/struct_decl_test.cc"
  "lang/wgsl/reader/parser/struct_member_attribute_decl_test.cc"
  "lang/wgsl/reader/parser/struct_member_attribute_test.cc"
  "lang/wgsl/reader/parser/struct_member_test.cc"
  "lang/wgsl/reader/parser/switch_body_test.cc"
  "lang/wgsl/reader/parser/switch_stmt_test.cc"
  "lang/wgsl/reader/parser/token_test.cc"
  "lang/wgsl/reader/parser/type_alias_test.cc"
  "lang/wgsl/reader/parser/type_decl_test.cc"
  "lang/wgsl/reader/parser/unary_expression_test.cc"
  "lang/wgsl/reader/parser/variable_attribute_list_test.cc"
  "lang/wgsl/reader/parser/variable_attribute_test.cc"
  "lang/wgsl/reader/parser/variable_decl_test.cc"
  "lang/wgsl/reader/parser/variable_ident_decl_test.cc"
  "lang/wgsl/reader/parser/variable_qualifier_test.cc"
  "lang/wgsl/reader/parser/variable_stmt_test.cc"
  "lang/wgsl/reader/parser/while_stmt_test.cc"
)

target_link_libraries(tint_unittests
  lib_tint_lang_core_builtin
  lib_tint_lang_core_type
  lib_tint_lang_wgsl_ast
  lib_tint_lang_wgsl_reader_parser
  lib_tint_utils_containers
  lib_tint_utils_text
)



