// Copyright 2022 The Tint Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

////////////////////////////////////////////////////////////////////////////////
// File generated by tools/src/cmd/gen
// using the template:
//   src/tint/type/short_name_test.cc.tmpl
//
// Do not modify this file directly
////////////////////////////////////////////////////////////////////////////////

#include "src/tint/type/short_name.h"

#include <string>

#include "gtest/gtest.h"

#include "src/tint/utils/string.h"

namespace tint::type {
namespace {

namespace parse_print_tests {

struct Case {
    const char* string;
    ShortName value;
};

inline std::ostream& operator<<(std::ostream& out, Case c) {
    return out << "'" << std::string(c.string) << "'";
}

static constexpr Case kValidCases[] = {
    {"bool", ShortName::kBool},       {"f16", ShortName::kF16},
    {"f32", ShortName::kF32},         {"i32", ShortName::kI32},
    {"mat2x2f", ShortName::kMat2X2F}, {"mat2x2h", ShortName::kMat2X2H},
    {"mat2x3f", ShortName::kMat2X3F}, {"mat2x3h", ShortName::kMat2X3H},
    {"mat2x4f", ShortName::kMat2X4F}, {"mat2x4h", ShortName::kMat2X4H},
    {"mat3x2f", ShortName::kMat3X2F}, {"mat3x2h", ShortName::kMat3X2H},
    {"mat3x3f", ShortName::kMat3X3F}, {"mat3x3h", ShortName::kMat3X3H},
    {"mat3x4f", ShortName::kMat3X4F}, {"mat3x4h", ShortName::kMat3X4H},
    {"mat4x2f", ShortName::kMat4X2F}, {"mat4x2h", ShortName::kMat4X2H},
    {"mat4x3f", ShortName::kMat4X3F}, {"mat4x3h", ShortName::kMat4X3H},
    {"mat4x4f", ShortName::kMat4X4F}, {"mat4x4h", ShortName::kMat4X4H},
    {"u32", ShortName::kU32},         {"vec2f", ShortName::kVec2F},
    {"vec2h", ShortName::kVec2H},     {"vec2i", ShortName::kVec2I},
    {"vec2u", ShortName::kVec2U},     {"vec3f", ShortName::kVec3F},
    {"vec3h", ShortName::kVec3H},     {"vec3i", ShortName::kVec3I},
    {"vec3u", ShortName::kVec3U},     {"vec4f", ShortName::kVec4F},
    {"vec4h", ShortName::kVec4H},     {"vec4i", ShortName::kVec4I},
    {"vec4u", ShortName::kVec4U},
};

static constexpr Case kInvalidCases[] = {
    {"ccol", ShortName::kUndefined},        {"3", ShortName::kUndefined},
    {"bVol", ShortName::kUndefined},        {"116", ShortName::kUndefined},
    {"qJ6", ShortName::kUndefined},         {"f17ll", ShortName::kUndefined},
    {"fppqH", ShortName::kUndefined},       {"", ShortName::kUndefined},
    {"Gb", ShortName::kUndefined},          {"i3vi", ShortName::kUndefined},
    {"i8WW", ShortName::kUndefined},        {"ixx", ShortName::kUndefined},
    {"mX2x2gg", ShortName::kUndefined},     {"a2xXf", ShortName::kUndefined},
    {"mat232f", ShortName::kUndefined},     {"Eat2x2h", ShortName::kUndefined},
    {"mPTT2x2h", ShortName::kUndefined},    {"mat2xdxx", ShortName::kUndefined},
    {"m44t2x3f", ShortName::kUndefined},    {"maSS2xVVf", ShortName::kUndefined},
    {"RatR22f", ShortName::kUndefined},     {"mF2x9h", ShortName::kUndefined},
    {"matx3h", ShortName::kUndefined},      {"VOORRH3h", ShortName::kUndefined},
    {"ma2xyf", ShortName::kUndefined},      {"llnarr2774f", ShortName::kUndefined},
    {"mat24400", ShortName::kUndefined},    {"a2ooh", ShortName::kUndefined},
    {"zz2x4h", ShortName::kUndefined},      {"miitppx1", ShortName::kUndefined},
    {"mat3xXXf", ShortName::kUndefined},    {"9II5ann3x2f", ShortName::kUndefined},
    {"mataSSrHHYf", ShortName::kUndefined}, {"makkh", ShortName::kUndefined},
    {"jatgRx", ShortName::kUndefined},      {"mb3x2", ShortName::kUndefined},
    {"mat3xjf", ShortName::kUndefined},     {"at3x3f", ShortName::kUndefined},
    {"q3x3f", ShortName::kUndefined},       {"matNN3h", ShortName::kUndefined},
    {"at33vv", ShortName::kUndefined},      {"QQt3x3h", ShortName::kUndefined},
    {"maffxr", ShortName::kUndefined},      {"mat3xjf", ShortName::kUndefined},
    {"mNNw3x48", ShortName::kUndefined},    {"matx4h", ShortName::kUndefined},
    {"mrrt3x4h", ShortName::kUndefined},    {"Gat3x4h", ShortName::kUndefined},
    {"mat4x2FF", ShortName::kUndefined},    {"at4f", ShortName::kUndefined},
    {"marrx2f", ShortName::kUndefined},     {"t4x2h", ShortName::kUndefined},
    {"Da4xJJh", ShortName::kUndefined},     {"ma82", ShortName::kUndefined},
    {"m11k3", ShortName::kUndefined},       {"matx3f", ShortName::kUndefined},
    {"maJx3f", ShortName::kUndefined},      {"mat4c3h", ShortName::kUndefined},
    {"mat4x3O", ShortName::kUndefined},     {"KK_atvvtt3h", ShortName::kUndefined},
    {"xx84x4f", ShortName::kUndefined},     {"__qatF4", ShortName::kUndefined},
    {"matqx4f", ShortName::kUndefined},     {"33atOx4h", ShortName::kUndefined},
    {"mtt64x9oQQ", ShortName::kUndefined},  {"ma4x66h", ShortName::kUndefined},
    {"zzO6", ShortName::kUndefined},        {"uyy2", ShortName::kUndefined},
    {"HZ", ShortName::kUndefined},          {"ecWq4f", ShortName::kUndefined},
    {"vOO2f", ShortName::kUndefined},       {"oYe2", ShortName::kUndefined},
    {"v2", ShortName::kUndefined},          {"Fe2h", ShortName::kUndefined},
    {"vwch", ShortName::kUndefined},        {"vefi", ShortName::kUndefined},
    {"KKeq2i", ShortName::kUndefined},      {"vFmm2i", ShortName::kUndefined},
    {"vecu", ShortName::kUndefined},        {"qc2u", ShortName::kUndefined},
    {"vecbb", ShortName::kUndefined},       {"iic3", ShortName::kUndefined},
    {"vqOOf", ShortName::kUndefined},       {"vevvTTf", ShortName::kUndefined},
    {"veFF3h", ShortName::kUndefined},      {"00PfQ", ShortName::kUndefined},
    {"vec3P", ShortName::kUndefined},       {"vec77s", ShortName::kUndefined},
    {"vecbbCi", ShortName::kUndefined},     {"vecXXi", ShortName::kUndefined},
    {"CCOOec3", ShortName::kUndefined},     {"vs3u", ShortName::kUndefined},
    {"Xec3u", ShortName::kUndefined},       {"ve4f", ShortName::kUndefined},
    {"qq4", ShortName::kUndefined},         {"vec422", ShortName::kUndefined},
    {"vezzXy", ShortName::kUndefined},      {"ieVVP", ShortName::kUndefined},
    {"venCh", ShortName::kUndefined},       {"vHc4Aq", ShortName::kUndefined},
    {"ve4i", ShortName::kUndefined},        {"vefK", ShortName::kUndefined},
    {"vgg4", ShortName::kUndefined},        {"vecu", ShortName::kUndefined},
    {"4TNc4u", ShortName::kUndefined},
};

using ShortNameParseTest = testing::TestWithParam<Case>;

TEST_P(ShortNameParseTest, Parse) {
    const char* string = GetParam().string;
    ShortName expect = GetParam().value;
    EXPECT_EQ(expect, ParseShortName(string));
}

INSTANTIATE_TEST_SUITE_P(ValidCases, ShortNameParseTest, testing::ValuesIn(kValidCases));
INSTANTIATE_TEST_SUITE_P(InvalidCases, ShortNameParseTest, testing::ValuesIn(kInvalidCases));

using ShortNamePrintTest = testing::TestWithParam<Case>;

TEST_P(ShortNamePrintTest, Print) {
    ShortName value = GetParam().value;
    const char* expect = GetParam().string;
    EXPECT_EQ(expect, utils::ToString(value));
}

INSTANTIATE_TEST_SUITE_P(ValidCases, ShortNamePrintTest, testing::ValuesIn(kValidCases));

}  // namespace parse_print_tests

}  // namespace
}  // namespace tint::type
