# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


add_library(lib_tint_lang_glsl_writer_ast_printer STATIC
  "lang/glsl/writer/ast_printer/ast_printer.cc"
  "lang/glsl/writer/ast_printer/ast_printer.h"
)

target_link_libraries(lib_tint_lang_glsl_writer_ast_printer
  lib_tint_lang_core_builtin
  lib_tint_lang_core_constant
  lib_tint_lang_core_type
  lib_tint_lang_glsl_writer_common
  lib_tint_lang_wgsl_ast
  lib_tint_lang_wgsl_ast_transform
  lib_tint_lang_wgsl_helpers
  lib_tint_lang_wgsl_program
  lib_tint_lang_wgsl_sem
  lib_tint_utils_containers
  lib_tint_utils_generator
  lib_tint_utils_ice
  lib_tint_utils_macros
  lib_tint_utils_math
  lib_tint_utils_rtti
  lib_tint_utils_strconv
  lib_tint_utils_text
)

tint_default_compile_options(lib_tint_lang_glsl_writer_ast_printer)

target_sources(tint_unittests PRIVATE
  "lang/glsl/writer/ast_printer/array_accessor_test.cc"
  "lang/glsl/writer/ast_printer/assign_test.cc"
  "lang/glsl/writer/ast_printer/ast_printer_test.cc"
  "lang/glsl/writer/ast_printer/binary_test.cc"
  "lang/glsl/writer/ast_printer/bitcast_test.cc"
  "lang/glsl/writer/ast_printer/block_test.cc"
  "lang/glsl/writer/ast_printer/break_test.cc"
  "lang/glsl/writer/ast_printer/builtin_test.cc"
  "lang/glsl/writer/ast_printer/builtin_texture_test.cc"
  "lang/glsl/writer/ast_printer/call_test.cc"
  "lang/glsl/writer/ast_printer/case_test.cc"
  "lang/glsl/writer/ast_printer/cast_test.cc"
  "lang/glsl/writer/ast_printer/constructor_test.cc"
  "lang/glsl/writer/ast_printer/continue_test.cc"
  "lang/glsl/writer/ast_printer/discard_test.cc"
  "lang/glsl/writer/ast_printer/function_test.cc"
  "lang/glsl/writer/ast_printer/helper_test.h"
  "lang/glsl/writer/ast_printer/identifier_test.cc"
  "lang/glsl/writer/ast_printer/if_test.cc"
  "lang/glsl/writer/ast_printer/import_test.cc"
  "lang/glsl/writer/ast_printer/loop_test.cc"
  "lang/glsl/writer/ast_printer/member_accessor_test.cc"
  "lang/glsl/writer/ast_printer/module_constant_test.cc"
  "lang/glsl/writer/ast_printer/return_test.cc"
  "lang/glsl/writer/ast_printer/sanitizer_test.cc"
  "lang/glsl/writer/ast_printer/storage_buffer_test.cc"
  "lang/glsl/writer/ast_printer/switch_test.cc"
  "lang/glsl/writer/ast_printer/type_test.cc"
  "lang/glsl/writer/ast_printer/unary_op_test.cc"
  "lang/glsl/writer/ast_printer/uniform_buffer_test.cc"
  "lang/glsl/writer/ast_printer/variable_decl_statement_test.cc"
  "lang/glsl/writer/ast_printer/workgroup_var_test.cc"
)

target_link_libraries(tint_unittests
  lib_tint_lang_core_builtin
  lib_tint_lang_core_type
  lib_tint_lang_glsl_writer
  lib_tint_lang_glsl_writer_ast_printer
  lib_tint_lang_glsl_writer_common
  lib_tint_lang_wgsl_ast
  lib_tint_lang_wgsl_ast_transform
  lib_tint_lang_wgsl_resolver
  lib_tint_lang_wgsl_sem
  lib_tint_utils_text
)



