# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################

include(lang/wgsl/ast/BUILD.cmake)
include(lang/wgsl/helpers/BUILD.cmake)
include(lang/wgsl/inspector/BUILD.cmake)
include(lang/wgsl/program/BUILD.cmake)
include(lang/wgsl/reader/BUILD.cmake)
include(lang/wgsl/resolver/BUILD.cmake)
include(lang/wgsl/sem/BUILD.cmake)
include(lang/wgsl/writer/BUILD.cmake)

tint_target_sources(tint_unittests
  "lang/wgsl/ir_roundtrip_test.cc"
)

tint_target_link_tint_libraries(tint_unittests
  tint_lang_wgsl_reader
  tint_lang_wgsl_reader_program_to_ir
  tint_lang_wgsl_writer
  tint_lang_wgsl_writer_ir_to_program
  tint_utils_text
)

