# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


add_executable(tint_cmd_tint_cmd
  "cmd/tint/main.cc"
)

target_link_libraries(tint_cmd_tint_cmd
  lib_tint_cmd_common
  lib_tint_lang_core_ir
  lib_tint_lang_glsl_writer
  lib_tint_lang_hlsl_validate
  lib_tint_lang_hlsl_writer
  lib_tint_lang_msl_validate
  lib_tint_lang_msl_writer
  lib_tint_lang_spirv_reader
  lib_tint_lang_spirv_writer
  lib_tint_lang_wgsl_ast
  lib_tint_lang_wgsl_reader
  lib_tint_lang_wgsl_reader_program_to_ir
  lib_tint_lang_wgsl_writer
  lib_tint_utils_cli
  lib_tint_utils_command
  lib_tint_utils_containers
  lib_tint_utils_diagnostic
  lib_tint_utils_macros
  lib_tint_utils_text
)

tint_default_compile_options(tint_cmd_tint_cmd)

