# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


add_library(lib_tint_lang_spirv_writer_ast_printer STATIC
  ast_printer.cc
  ast_printer.h
  builder.cc
  builder.h
  scalar_constant.h
)

target_link_libraries(lib_tint_lang_spirv_writer_ast_printer
  lib_tint_lang_core_builtin
  lib_tint_lang_core_constant
  lib_tint_lang_core_type
  lib_tint_lang_spirv_writer_common
  lib_tint_lang_wgsl_ast
  lib_tint_lang_wgsl_ast_transform
  lib_tint_lang_wgsl_helpers
  lib_tint_lang_wgsl_program
  lib_tint_lang_wgsl_sem
  lib_tint_utils_containers
  lib_tint_utils_macros
  lib_tint_utils_math
  lib_tint_utils_text
)

add_library(tint_lang_spirv_writer_ast_printer:test STATIC
  accessor_expression_test.cc
  assign_test.cc
  ast_builtin_test.cc
  ast_discard_test.cc
  ast_function_test.cc
  ast_if_test.cc
  ast_loop_test.cc
  ast_printer_test.cc
  ast_switch_test.cc
  ast_type_test.cc
  binary_expression_test.cc
  bitcast_expression_test.cc
  block_test.cc
  builtin_texture_test.cc
  call_test.cc
  const_assert_test.cc
  constructor_expression_test.cc
  entry_point_test.cc
  format_conversion_test.cc
  function_attribute_test.cc
  function_variable_test.cc
  global_variable_test.cc
  helper_test.h
  ident_expression_test.cc
  literal_test.cc
  return_test.cc
  scalar_constant_test.cc
  unary_op_expression_test.cc
)

target_link_libraries(tint_lang_spirv_writer_ast_printer:test
  lib_tint_lang_core_builtin
  lib_tint_lang_core_type
  lib_tint_lang_spirv_writer
  lib_tint_lang_spirv_writer_ast_printer
  lib_tint_lang_spirv_writer_common
  lib_tint_lang_wgsl_ast
  tint_lang_wgsl_ast:test
  lib_tint_lang_wgsl_program
  lib_tint_lang_wgsl_resolver
  lib_tint_utils_text
)

