# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################

include(lang/spirv/reader/ast_parser/BUILD.cmake)
include(lang/spirv/reader/common/BUILD.cmake)

add_library(lib_tint_lang_spirv_reader STATIC
  "lang/spirv/reader/reader.cc"
  "lang/spirv/reader/reader.h"
)

target_link_libraries(lib_tint_lang_spirv_reader
  lib_tint_lang_spirv_reader_ast_parser
  lib_tint_lang_spirv_reader_common
  lib_tint_lang_wgsl_program
)

tint_default_compile_options(lib_tint_lang_spirv_reader)

