# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


add_library(lib_tint_lang_msl_writer_printer STATIC
  "lang/msl/writer/printer/printer.cc"
  "lang/msl/writer/printer/printer.h"
)

target_link_libraries(lib_tint_lang_msl_writer_printer
  lib_tint_lang_core_constant
  lib_tint_lang_core_ir
  lib_tint_lang_core_type
  lib_tint_lang_msl_writer_common
  lib_tint_utils_containers
  lib_tint_utils_diagnostic
  lib_tint_utils_generator
  lib_tint_utils_macros
  lib_tint_utils_rtti
  lib_tint_utils_text
)

tint_default_compile_options(lib_tint_lang_msl_writer_printer)

target_sources(tint_unittests PRIVATE
  "lang/msl/writer/printer/constant_test.cc"
  "lang/msl/writer/printer/function_test.cc"
  "lang/msl/writer/printer/helper_test.h"
  "lang/msl/writer/printer/type_test.cc"
)

target_link_libraries(tint_unittests
  lib_tint_lang_core_ir
  lib_tint_lang_core_type
  lib_tint_lang_msl_writer_printer
  lib_tint_utils_text
)



