# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


add_library(lib_tint_lang_wgsl_reader_program_to_ir STATIC
  program_to_ir.cc
  program_to_ir.h
)

target_link_libraries(lib_tint_lang_wgsl_reader_program_to_ir
  lib_tint_lang_core_ir
  lib_tint_lang_core_type
  lib_tint_lang_wgsl_ast
  lib_tint_lang_wgsl_program
  lib_tint_lang_wgsl_sem
  lib_tint_utils_containers
  lib_tint_utils_macros
  lib_tint_utils_result
  lib_tint_utils_rtti
)

add_library(tint_lang_wgsl_reader_program_to_ir:test STATIC
  accessor_test.cc
  binary_test.cc
  builtin_test.cc
  call_test.cc
  function_test.cc
  let_test.cc
  literal_test.cc
  materialize_test.cc
  program_to_ir_test.cc
  shadowing_test.cc
  store_test.cc
  unary_test.cc
  var_test.cc
)

target_link_libraries(tint_lang_wgsl_reader_program_to_ir:test
  lib_tint_lang_core_constant
  lib_tint_lang_core_ir
  lib_tint_lang_wgsl_ast
  tint_lang_wgsl_helpers:test
)

