# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


tint_add_library(tint_lang_wgsl_reader_program_to_ir
  "lang/wgsl/reader/program_to_ir/program_to_ir.cc"
  "lang/wgsl/reader/program_to_ir/program_to_ir.h"
)

tint_target_link_tint_libraries(tint_lang_wgsl_reader_program_to_ir
  tint_lang_core_ir
  tint_lang_core_type
  tint_lang_wgsl_ast
  tint_lang_wgsl_program
  tint_lang_wgsl_sem
  tint_utils_containers
  tint_utils_macros
  tint_utils_result
  tint_utils_rtti
)

tint_target_sources(tint_unittests
  "lang/wgsl/reader/program_to_ir/accessor_test.cc"
  "lang/wgsl/reader/program_to_ir/binary_test.cc"
  "lang/wgsl/reader/program_to_ir/builtin_test.cc"
  "lang/wgsl/reader/program_to_ir/call_test.cc"
  "lang/wgsl/reader/program_to_ir/function_test.cc"
  "lang/wgsl/reader/program_to_ir/let_test.cc"
  "lang/wgsl/reader/program_to_ir/literal_test.cc"
  "lang/wgsl/reader/program_to_ir/materialize_test.cc"
  "lang/wgsl/reader/program_to_ir/program_to_ir_test.cc"
  "lang/wgsl/reader/program_to_ir/shadowing_test.cc"
  "lang/wgsl/reader/program_to_ir/store_test.cc"
  "lang/wgsl/reader/program_to_ir/unary_test.cc"
  "lang/wgsl/reader/program_to_ir/var_test.cc"
)

tint_target_link_tint_libraries(tint_unittests
  tint_lang_core_constant
  tint_lang_core_ir
  tint_lang_wgsl_ast
)

