# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


add_library(lib_tint_lang_core_type STATIC
  abstract_float.cc
  abstract_float.h
  abstract_int.cc
  abstract_int.h
  abstract_numeric.cc
  abstract_numeric.h
  array.cc
  array.h
  array_count.cc
  array_count.h
  atomic.cc
  atomic.h
  bool.cc
  bool.h
  builtin_structs.cc
  builtin_structs.h
  clone_context.h
  depth_multisampled_texture.cc
  depth_multisampled_texture.h
  depth_texture.cc
  depth_texture.h
  external_texture.cc
  external_texture.h
  f16.cc
  f16.h
  f32.cc
  f32.h
  i32.cc
  i32.h
  manager.cc
  manager.h
  matrix.cc
  matrix.h
  multisampled_texture.cc
  multisampled_texture.h
  node.cc
  node.h
  numeric_scalar.cc
  numeric_scalar.h
  pointer.cc
  pointer.h
  reference.cc
  reference.h
  sampled_texture.cc
  sampled_texture.h
  sampler.cc
  sampler.h
  sampler_kind.cc
  sampler_kind.h
  scalar.cc
  scalar.h
  storage_texture.cc
  storage_texture.h
  struct.cc
  struct.h
  texture.cc
  texture.h
  texture_dimension.cc
  texture_dimension.h
  type.cc
  type.h
  u32.cc
  u32.h
  unique_node.cc
  unique_node.h
  vector.cc
  vector.h
  void.cc
  void.h
)

target_link_libraries(lib_tint_lang_core_type
  lib_tint_lang_core_builtin
  lib_tint_utils_containers
  lib_tint_utils_diagnostic
  lib_tint_utils_ice
  lib_tint_utils_macros
  lib_tint_utils_math
  lib_tint_utils_rtti
  lib_tint_utils_symbol
  lib_tint_utils_text
  lib_tint_utils_traits
)

add_library(tint_lang_core_type:test STATIC
  array_test.cc
  atomic_test.cc
  bool_test.cc
  builtin_structs_test.cc
  depth_multisampled_texture_test.cc
  depth_texture_test.cc
  external_texture_test.cc
  f16_test.cc
  f32_test.cc
  helper_test.h
  i32_test.cc
  manager_test.cc
  matrix_test.cc
  multisampled_texture_test.cc
  pointer_test.cc
  reference_test.cc
  sampled_texture_test.cc
  sampler_test.cc
  storage_texture_test.cc
  struct_test.cc
  texture_test.cc
  type_test.cc
  u32_test.cc
  vector_test.cc
)

target_link_libraries(tint_lang_core_type:test
  lib_tint_lang_core_builtin
  lib_tint_lang_core_type
  lib_tint_lang_wgsl_program
  lib_tint_lang_wgsl_resolver
  lib_tint_lang_wgsl_sem
  lib_tint_utils_id
  lib_tint_utils_symbol
)

