# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


tint_add_library(tint_lang_core_builtin
  "lang/core/builtin/access.cc"
  "lang/core/builtin/access.h"
  "lang/core/builtin/address_space.cc"
  "lang/core/builtin/address_space.h"
  "lang/core/builtin/attribute.cc"
  "lang/core/builtin/attribute.h"
  "lang/core/builtin/builtin.cc"
  "lang/core/builtin/builtin.h"
  "lang/core/builtin/builtin_value.cc"
  "lang/core/builtin/builtin_value.h"
  "lang/core/builtin/diagnostic_rule.cc"
  "lang/core/builtin/diagnostic_rule.h"
  "lang/core/builtin/diagnostic_severity.cc"
  "lang/core/builtin/diagnostic_severity.h"
  "lang/core/builtin/extension.cc"
  "lang/core/builtin/extension.h"
  "lang/core/builtin/fluent_types.h"
  "lang/core/builtin/function.cc"
  "lang/core/builtin/function.h"
  "lang/core/builtin/interpolation.h"
  "lang/core/builtin/interpolation_sampling.cc"
  "lang/core/builtin/interpolation_sampling.h"
  "lang/core/builtin/interpolation_type.cc"
  "lang/core/builtin/interpolation_type.h"
  "lang/core/builtin/number.cc"
  "lang/core/builtin/number.h"
  "lang/core/builtin/texel_format.cc"
  "lang/core/builtin/texel_format.h"
)

tint_target_link_tint_libraries(tint_lang_core_builtin
  tint_utils_containers
  tint_utils_diagnostic
  tint_utils_ice
  tint_utils_macros
  tint_utils_memory
  tint_utils_result
  tint_utils_text
  tint_utils_traits
)

tint_target_sources(tint_unittests
  "lang/core/builtin/access_test.cc"
  "lang/core/builtin/address_space_test.cc"
  "lang/core/builtin/attribute_test.cc"
  "lang/core/builtin/builtin_test.cc"
  "lang/core/builtin/builtin_value_test.cc"
  "lang/core/builtin/diagnostic_rule_test.cc"
  "lang/core/builtin/diagnostic_severity_test.cc"
  "lang/core/builtin/extension_test.cc"
  "lang/core/builtin/interpolation_sampling_test.cc"
  "lang/core/builtin/interpolation_type_test.cc"
  "lang/core/builtin/number_test.cc"
  "lang/core/builtin/texel_format_test.cc"
)

tint_target_link_tint_libraries(tint_unittests
  tint_lang_core_builtin
  tint_lang_wgsl_program
  tint_utils_macros
  tint_utils_text
)

tint_target_sources(tint_benchmark
  "lang/core/builtin/access_bench.cc"
  "lang/core/builtin/address_space_bench.cc"
  "lang/core/builtin/attribute_bench.cc"
  "lang/core/builtin/builtin_bench.cc"
  "lang/core/builtin/builtin_value_bench.cc"
  "lang/core/builtin/diagnostic_rule_bench.cc"
  "lang/core/builtin/diagnostic_severity_bench.cc"
  "lang/core/builtin/extension_bench.cc"
  "lang/core/builtin/interpolation_sampling_bench.cc"
  "lang/core/builtin/interpolation_type_bench.cc"
  "lang/core/builtin/texel_format_bench.cc"
)

tint_target_link_tint_libraries(tint_benchmark
  tint_lang_core_builtin
)

