# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


add_library(lib_tint_lang_core_builtin STATIC
  access.cc
  access.h
  address_space.cc
  address_space.h
  attribute.cc
  attribute.h
  builtin.cc
  builtin.h
  builtin_value.cc
  builtin_value.h
  diagnostic_rule.cc
  diagnostic_rule.h
  diagnostic_severity.cc
  diagnostic_severity.h
  extension.cc
  extension.h
  fluent_types.h
  function.cc
  function.h
  interpolation.h
  interpolation_sampling.cc
  interpolation_sampling.h
  interpolation_type.cc
  interpolation_type.h
  number.cc
  number.h
  texel_format.cc
  texel_format.h
)

target_link_libraries(lib_tint_lang_core_builtin
  lib_tint_utils_containers
  lib_tint_utils_diagnostic
  lib_tint_utils_ice
  lib_tint_utils_macros
  lib_tint_utils_memory
  lib_tint_utils_result
  lib_tint_utils_text
  lib_tint_utils_traits
)

add_library(tint_lang_core_builtin:test STATIC
  access_test.cc
  address_space_test.cc
  attribute_test.cc
  builtin_test.cc
  builtin_value_test.cc
  diagnostic_rule_test.cc
  diagnostic_severity_test.cc
  extension_test.cc
  interpolation_sampling_test.cc
  interpolation_type_test.cc
  number_test.cc
  texel_format_test.cc
)

target_link_libraries(tint_lang_core_builtin:test
  lib_tint_lang_core_builtin
  lib_tint_lang_wgsl_program
  lib_tint_utils_macros
  lib_tint_utils_text
)

