#version 310 es

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
void unused_entry_point() {
  return;
}
struct S {
  vec3 v;
};

layout(binding = 0) uniform S_1 {
  S _;
} U;

void f() {
  vec3 v = U._.v;
  float x = U._.v.x;
  float y = U._.v.y;
  float z = U._.v.z;
  vec2 xx = U._.v.xx;
  vec2 xy = U._.v.xy;
  vec2 xz = U._.v.xz;
  vec2 yx = U._.v.yx;
  vec2 yy = U._.v.yy;
  vec2 yz = U._.v.yz;
  vec2 zx = U._.v.zx;
  vec2 zy = U._.v.zy;
  vec2 zz = U._.v.zz;
  vec3 xxx = U._.v.xxx;
  vec3 xxy = U._.v.xxy;
  vec3 xxz = U._.v.xxz;
  vec3 xyx = U._.v.xyx;
  vec3 xyy = U._.v.xyy;
  vec3 xyz = U._.v.xyz;
  vec3 xzx = U._.v.xzx;
  vec3 xzy = U._.v.xzy;
  vec3 xzz = U._.v.xzz;
  vec3 yxx = U._.v.yxx;
  vec3 yxy = U._.v.yxy;
  vec3 yxz = U._.v.yxz;
  vec3 yyx = U._.v.yyx;
  vec3 yyy = U._.v.yyy;
  vec3 yyz = U._.v.yyz;
  vec3 yzx = U._.v.yzx;
  vec3 yzy = U._.v.yzy;
  vec3 yzz = U._.v.yzz;
  vec3 zxx = U._.v.zxx;
  vec3 zxy = U._.v.zxy;
  vec3 zxz = U._.v.zxz;
  vec3 zyx = U._.v.zyx;
  vec3 zyy = U._.v.zyy;
  vec3 zyz = U._.v.zyz;
  vec3 zzx = U._.v.zzx;
  vec3 zzy = U._.v.zzy;
  vec3 zzz = U._.v.zzz;
  vec4 xxxx = U._.v.xxxx;
  vec4 xxxy = U._.v.xxxy;
  vec4 xxxz = U._.v.xxxz;
  vec4 xxyx = U._.v.xxyx;
  vec4 xxyy = U._.v.xxyy;
  vec4 xxyz = U._.v.xxyz;
  vec4 xxzx = U._.v.xxzx;
  vec4 xxzy = U._.v.xxzy;
  vec4 xxzz = U._.v.xxzz;
  vec4 xyxx = U._.v.xyxx;
  vec4 xyxy = U._.v.xyxy;
  vec4 xyxz = U._.v.xyxz;
  vec4 xyyx = U._.v.xyyx;
  vec4 xyyy = U._.v.xyyy;
  vec4 xyyz = U._.v.xyyz;
  vec4 xyzx = U._.v.xyzx;
  vec4 xyzy = U._.v.xyzy;
  vec4 xyzz = U._.v.xyzz;
  vec4 xzxx = U._.v.xzxx;
  vec4 xzxy = U._.v.xzxy;
  vec4 xzxz = U._.v.xzxz;
  vec4 xzyx = U._.v.xzyx;
  vec4 xzyy = U._.v.xzyy;
  vec4 xzyz = U._.v.xzyz;
  vec4 xzzx = U._.v.xzzx;
  vec4 xzzy = U._.v.xzzy;
  vec4 xzzz = U._.v.xzzz;
  vec4 yxxx = U._.v.yxxx;
  vec4 yxxy = U._.v.yxxy;
  vec4 yxxz = U._.v.yxxz;
  vec4 yxyx = U._.v.yxyx;
  vec4 yxyy = U._.v.yxyy;
  vec4 yxyz = U._.v.yxyz;
  vec4 yxzx = U._.v.yxzx;
  vec4 yxzy = U._.v.yxzy;
  vec4 yxzz = U._.v.yxzz;
  vec4 yyxx = U._.v.yyxx;
  vec4 yyxy = U._.v.yyxy;
  vec4 yyxz = U._.v.yyxz;
  vec4 yyyx = U._.v.yyyx;
  vec4 yyyy = U._.v.yyyy;
  vec4 yyyz = U._.v.yyyz;
  vec4 yyzx = U._.v.yyzx;
  vec4 yyzy = U._.v.yyzy;
  vec4 yyzz = U._.v.yyzz;
  vec4 yzxx = U._.v.yzxx;
  vec4 yzxy = U._.v.yzxy;
  vec4 yzxz = U._.v.yzxz;
  vec4 yzyx = U._.v.yzyx;
  vec4 yzyy = U._.v.yzyy;
  vec4 yzyz = U._.v.yzyz;
  vec4 yzzx = U._.v.yzzx;
  vec4 yzzy = U._.v.yzzy;
  vec4 yzzz = U._.v.yzzz;
  vec4 zxxx = U._.v.zxxx;
  vec4 zxxy = U._.v.zxxy;
  vec4 zxxz = U._.v.zxxz;
  vec4 zxyx = U._.v.zxyx;
  vec4 zxyy = U._.v.zxyy;
  vec4 zxyz = U._.v.zxyz;
  vec4 zxzx = U._.v.zxzx;
  vec4 zxzy = U._.v.zxzy;
  vec4 zxzz = U._.v.zxzz;
  vec4 zyxx = U._.v.zyxx;
  vec4 zyxy = U._.v.zyxy;
  vec4 zyxz = U._.v.zyxz;
  vec4 zyyx = U._.v.zyyx;
  vec4 zyyy = U._.v.zyyy;
  vec4 zyyz = U._.v.zyyz;
  vec4 zyzx = U._.v.zyzx;
  vec4 zyzy = U._.v.zyzy;
  vec4 zyzz = U._.v.zyzz;
  vec4 zzxx = U._.v.zzxx;
  vec4 zzxy = U._.v.zzxy;
  vec4 zzxz = U._.v.zzxz;
  vec4 zzyx = U._.v.zzyx;
  vec4 zzyy = U._.v.zzyy;
  vec4 zzyz = U._.v.zzyz;
  vec4 zzzx = U._.v.zzzx;
  vec4 zzzy = U._.v.zzzy;
  vec4 zzzz = U._.v.zzzz;
}

