#version 310 es

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
void unused_entry_point() {
  return;
}
struct S {
  ivec3 v;
};

layout(binding = 0) uniform S_1 {
  S _;
} U;

void f() {
  ivec3 v = U._.v;
  int x = U._.v.x;
  int y = U._.v.y;
  int z = U._.v.z;
  ivec2 xx = U._.v.xx;
  ivec2 xy = U._.v.xy;
  ivec2 xz = U._.v.xz;
  ivec2 yx = U._.v.yx;
  ivec2 yy = U._.v.yy;
  ivec2 yz = U._.v.yz;
  ivec2 zx = U._.v.zx;
  ivec2 zy = U._.v.zy;
  ivec2 zz = U._.v.zz;
  ivec3 xxx = U._.v.xxx;
  ivec3 xxy = U._.v.xxy;
  ivec3 xxz = U._.v.xxz;
  ivec3 xyx = U._.v.xyx;
  ivec3 xyy = U._.v.xyy;
  ivec3 xyz = U._.v.xyz;
  ivec3 xzx = U._.v.xzx;
  ivec3 xzy = U._.v.xzy;
  ivec3 xzz = U._.v.xzz;
  ivec3 yxx = U._.v.yxx;
  ivec3 yxy = U._.v.yxy;
  ivec3 yxz = U._.v.yxz;
  ivec3 yyx = U._.v.yyx;
  ivec3 yyy = U._.v.yyy;
  ivec3 yyz = U._.v.yyz;
  ivec3 yzx = U._.v.yzx;
  ivec3 yzy = U._.v.yzy;
  ivec3 yzz = U._.v.yzz;
  ivec3 zxx = U._.v.zxx;
  ivec3 zxy = U._.v.zxy;
  ivec3 zxz = U._.v.zxz;
  ivec3 zyx = U._.v.zyx;
  ivec3 zyy = U._.v.zyy;
  ivec3 zyz = U._.v.zyz;
  ivec3 zzx = U._.v.zzx;
  ivec3 zzy = U._.v.zzy;
  ivec3 zzz = U._.v.zzz;
  ivec4 xxxx = U._.v.xxxx;
  ivec4 xxxy = U._.v.xxxy;
  ivec4 xxxz = U._.v.xxxz;
  ivec4 xxyx = U._.v.xxyx;
  ivec4 xxyy = U._.v.xxyy;
  ivec4 xxyz = U._.v.xxyz;
  ivec4 xxzx = U._.v.xxzx;
  ivec4 xxzy = U._.v.xxzy;
  ivec4 xxzz = U._.v.xxzz;
  ivec4 xyxx = U._.v.xyxx;
  ivec4 xyxy = U._.v.xyxy;
  ivec4 xyxz = U._.v.xyxz;
  ivec4 xyyx = U._.v.xyyx;
  ivec4 xyyy = U._.v.xyyy;
  ivec4 xyyz = U._.v.xyyz;
  ivec4 xyzx = U._.v.xyzx;
  ivec4 xyzy = U._.v.xyzy;
  ivec4 xyzz = U._.v.xyzz;
  ivec4 xzxx = U._.v.xzxx;
  ivec4 xzxy = U._.v.xzxy;
  ivec4 xzxz = U._.v.xzxz;
  ivec4 xzyx = U._.v.xzyx;
  ivec4 xzyy = U._.v.xzyy;
  ivec4 xzyz = U._.v.xzyz;
  ivec4 xzzx = U._.v.xzzx;
  ivec4 xzzy = U._.v.xzzy;
  ivec4 xzzz = U._.v.xzzz;
  ivec4 yxxx = U._.v.yxxx;
  ivec4 yxxy = U._.v.yxxy;
  ivec4 yxxz = U._.v.yxxz;
  ivec4 yxyx = U._.v.yxyx;
  ivec4 yxyy = U._.v.yxyy;
  ivec4 yxyz = U._.v.yxyz;
  ivec4 yxzx = U._.v.yxzx;
  ivec4 yxzy = U._.v.yxzy;
  ivec4 yxzz = U._.v.yxzz;
  ivec4 yyxx = U._.v.yyxx;
  ivec4 yyxy = U._.v.yyxy;
  ivec4 yyxz = U._.v.yyxz;
  ivec4 yyyx = U._.v.yyyx;
  ivec4 yyyy = U._.v.yyyy;
  ivec4 yyyz = U._.v.yyyz;
  ivec4 yyzx = U._.v.yyzx;
  ivec4 yyzy = U._.v.yyzy;
  ivec4 yyzz = U._.v.yyzz;
  ivec4 yzxx = U._.v.yzxx;
  ivec4 yzxy = U._.v.yzxy;
  ivec4 yzxz = U._.v.yzxz;
  ivec4 yzyx = U._.v.yzyx;
  ivec4 yzyy = U._.v.yzyy;
  ivec4 yzyz = U._.v.yzyz;
  ivec4 yzzx = U._.v.yzzx;
  ivec4 yzzy = U._.v.yzzy;
  ivec4 yzzz = U._.v.yzzz;
  ivec4 zxxx = U._.v.zxxx;
  ivec4 zxxy = U._.v.zxxy;
  ivec4 zxxz = U._.v.zxxz;
  ivec4 zxyx = U._.v.zxyx;
  ivec4 zxyy = U._.v.zxyy;
  ivec4 zxyz = U._.v.zxyz;
  ivec4 zxzx = U._.v.zxzx;
  ivec4 zxzy = U._.v.zxzy;
  ivec4 zxzz = U._.v.zxzz;
  ivec4 zyxx = U._.v.zyxx;
  ivec4 zyxy = U._.v.zyxy;
  ivec4 zyxz = U._.v.zyxz;
  ivec4 zyyx = U._.v.zyyx;
  ivec4 zyyy = U._.v.zyyy;
  ivec4 zyyz = U._.v.zyyz;
  ivec4 zyzx = U._.v.zyzx;
  ivec4 zyzy = U._.v.zyzy;
  ivec4 zyzz = U._.v.zyzz;
  ivec4 zzxx = U._.v.zzxx;
  ivec4 zzxy = U._.v.zzxy;
  ivec4 zzxz = U._.v.zzxz;
  ivec4 zzyx = U._.v.zzyx;
  ivec4 zzyy = U._.v.zzyy;
  ivec4 zzyz = U._.v.zzyz;
  ivec4 zzzx = U._.v.zzzx;
  ivec4 zzzy = U._.v.zzzy;
  ivec4 zzzz = U._.v.zzzz;
}

