#version 310 es

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
void unused_entry_point() {
  return;
}
struct S {
  uvec3 v;
};

layout(binding = 0) uniform S_1 {
  S _;
} U;

void f() {
  uvec3 v = U._.v;
  uint x = U._.v.x;
  uint y = U._.v.y;
  uint z = U._.v.z;
  uvec2 xx = U._.v.xx;
  uvec2 xy = U._.v.xy;
  uvec2 xz = U._.v.xz;
  uvec2 yx = U._.v.yx;
  uvec2 yy = U._.v.yy;
  uvec2 yz = U._.v.yz;
  uvec2 zx = U._.v.zx;
  uvec2 zy = U._.v.zy;
  uvec2 zz = U._.v.zz;
  uvec3 xxx = U._.v.xxx;
  uvec3 xxy = U._.v.xxy;
  uvec3 xxz = U._.v.xxz;
  uvec3 xyx = U._.v.xyx;
  uvec3 xyy = U._.v.xyy;
  uvec3 xyz = U._.v.xyz;
  uvec3 xzx = U._.v.xzx;
  uvec3 xzy = U._.v.xzy;
  uvec3 xzz = U._.v.xzz;
  uvec3 yxx = U._.v.yxx;
  uvec3 yxy = U._.v.yxy;
  uvec3 yxz = U._.v.yxz;
  uvec3 yyx = U._.v.yyx;
  uvec3 yyy = U._.v.yyy;
  uvec3 yyz = U._.v.yyz;
  uvec3 yzx = U._.v.yzx;
  uvec3 yzy = U._.v.yzy;
  uvec3 yzz = U._.v.yzz;
  uvec3 zxx = U._.v.zxx;
  uvec3 zxy = U._.v.zxy;
  uvec3 zxz = U._.v.zxz;
  uvec3 zyx = U._.v.zyx;
  uvec3 zyy = U._.v.zyy;
  uvec3 zyz = U._.v.zyz;
  uvec3 zzx = U._.v.zzx;
  uvec3 zzy = U._.v.zzy;
  uvec3 zzz = U._.v.zzz;
  uvec4 xxxx = U._.v.xxxx;
  uvec4 xxxy = U._.v.xxxy;
  uvec4 xxxz = U._.v.xxxz;
  uvec4 xxyx = U._.v.xxyx;
  uvec4 xxyy = U._.v.xxyy;
  uvec4 xxyz = U._.v.xxyz;
  uvec4 xxzx = U._.v.xxzx;
  uvec4 xxzy = U._.v.xxzy;
  uvec4 xxzz = U._.v.xxzz;
  uvec4 xyxx = U._.v.xyxx;
  uvec4 xyxy = U._.v.xyxy;
  uvec4 xyxz = U._.v.xyxz;
  uvec4 xyyx = U._.v.xyyx;
  uvec4 xyyy = U._.v.xyyy;
  uvec4 xyyz = U._.v.xyyz;
  uvec4 xyzx = U._.v.xyzx;
  uvec4 xyzy = U._.v.xyzy;
  uvec4 xyzz = U._.v.xyzz;
  uvec4 xzxx = U._.v.xzxx;
  uvec4 xzxy = U._.v.xzxy;
  uvec4 xzxz = U._.v.xzxz;
  uvec4 xzyx = U._.v.xzyx;
  uvec4 xzyy = U._.v.xzyy;
  uvec4 xzyz = U._.v.xzyz;
  uvec4 xzzx = U._.v.xzzx;
  uvec4 xzzy = U._.v.xzzy;
  uvec4 xzzz = U._.v.xzzz;
  uvec4 yxxx = U._.v.yxxx;
  uvec4 yxxy = U._.v.yxxy;
  uvec4 yxxz = U._.v.yxxz;
  uvec4 yxyx = U._.v.yxyx;
  uvec4 yxyy = U._.v.yxyy;
  uvec4 yxyz = U._.v.yxyz;
  uvec4 yxzx = U._.v.yxzx;
  uvec4 yxzy = U._.v.yxzy;
  uvec4 yxzz = U._.v.yxzz;
  uvec4 yyxx = U._.v.yyxx;
  uvec4 yyxy = U._.v.yyxy;
  uvec4 yyxz = U._.v.yyxz;
  uvec4 yyyx = U._.v.yyyx;
  uvec4 yyyy = U._.v.yyyy;
  uvec4 yyyz = U._.v.yyyz;
  uvec4 yyzx = U._.v.yyzx;
  uvec4 yyzy = U._.v.yyzy;
  uvec4 yyzz = U._.v.yyzz;
  uvec4 yzxx = U._.v.yzxx;
  uvec4 yzxy = U._.v.yzxy;
  uvec4 yzxz = U._.v.yzxz;
  uvec4 yzyx = U._.v.yzyx;
  uvec4 yzyy = U._.v.yzyy;
  uvec4 yzyz = U._.v.yzyz;
  uvec4 yzzx = U._.v.yzzx;
  uvec4 yzzy = U._.v.yzzy;
  uvec4 yzzz = U._.v.yzzz;
  uvec4 zxxx = U._.v.zxxx;
  uvec4 zxxy = U._.v.zxxy;
  uvec4 zxxz = U._.v.zxxz;
  uvec4 zxyx = U._.v.zxyx;
  uvec4 zxyy = U._.v.zxyy;
  uvec4 zxyz = U._.v.zxyz;
  uvec4 zxzx = U._.v.zxzx;
  uvec4 zxzy = U._.v.zxzy;
  uvec4 zxzz = U._.v.zxzz;
  uvec4 zyxx = U._.v.zyxx;
  uvec4 zyxy = U._.v.zyxy;
  uvec4 zyxz = U._.v.zyxz;
  uvec4 zyyx = U._.v.zyyx;
  uvec4 zyyy = U._.v.zyyy;
  uvec4 zyyz = U._.v.zyyz;
  uvec4 zyzx = U._.v.zyzx;
  uvec4 zyzy = U._.v.zyzy;
  uvec4 zyzz = U._.v.zyzz;
  uvec4 zzxx = U._.v.zzxx;
  uvec4 zzxy = U._.v.zzxy;
  uvec4 zzxz = U._.v.zzxz;
  uvec4 zzyx = U._.v.zzyx;
  uvec4 zzyy = U._.v.zzyy;
  uvec4 zzyz = U._.v.zzyz;
  uvec4 zzzx = U._.v.zzzx;
  uvec4 zzzy = U._.v.zzzy;
  uvec4 zzzz = U._.v.zzzz;
}

