package android.dawn

object Constants {
    val UINT32_MAX = Integer.parseUnsignedInt("4294967295")
    val UINT64_MAX = java.lang.Long.parseUnsignedLong("18446744073709551615")
    val SIZE_MAX = UINT64_MAX
    val ARRAY_LAYER_COUNT_UNDEFINED = UINT32_MAX;
    val COPY_STRIDE_UNDEFINED = UINT32_MAX;
    val DEPTH_SLICE_UNDEFINED = UINT32_MAX;
    val LIMIT_U32_UNDEFINED = UINT32_MAX;
    val LIMIT_U64_UNDEFINED = UINT64_MAX;
    val MIP_LEVEL_COUNT_UNDEFINED = UINT32_MAX;
    val QUERY_SET_INDEX_UNDEFINED = UINT32_MAX;
    val WHOLE_MAP_SIZE = SIZE_MAX;
    val WHOLE_SIZE = UINT64_MAX;
}
