// Copyright 2023 The Tint Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

////////////////////////////////////////////////////////////////////////////////
// File generated by tools/src/cmd/gen
// using the template:
//   src/tint/ir/builtins/gen.tmpl
//
// Do not modify this file directly
////////////////////////////////////////////////////////////////////////////////

#include "src/tint/ir/builtins/atan2.h"

TINT_INSTANTIATE_TYPEINFO(tint::ir::builtins::Atan2);

namespace tint::ir::builtins {

Atan2::Atan2(Value* result, utils::VectorRef<Value*> args) : Base(result, args) {}

Atan2::~Atan2() = default;

utils::StringStream& Atan2::ToString(utils::StringStream& out, const SymbolTable& st) const {
    Result()->ToString(out, st);
    out << " = atan2(";
    EmitArgs(out, st);
    out << ")";
    return out;
}

}  // namespace tint::ir::builtins
