// Copyright 2023 The Tint Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

////////////////////////////////////////////////////////////////////////////////
// File generated by tools/src/cmd/gen
// using the template:
//   src/tint/ir/builtins/gen.tmpl
//
// Do not modify this file directly
////////////////////////////////////////////////////////////////////////////////

#include "src/tint/ir/builtins/texture_sample_level.h"

TINT_INSTANTIATE_TYPEINFO(tint::ir::builtins::TextureSampleLevel);

namespace tint::ir::builtins {

TextureSampleLevel::TextureSampleLevel(Value* result, utils::VectorRef<Value*> args)
    : Base(result, args) {}

TextureSampleLevel::~TextureSampleLevel() = default;

utils::StringStream& TextureSampleLevel::ToString(utils::StringStream& out,
                                                  const SymbolTable& st) const {
    Result()->ToString(out, st);
    out << " = texture_sample_level(";
    EmitArgs(out, st);
    out << ")";
    return out;
}

}  // namespace tint::ir::builtins
