// Copyright 2020 The Tint Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

////////////////////////////////////////////////////////////////////////////////
// File generated by tools/src/cmd/gen
// using the template:
//   src/tint/ast/access.cc.tmpl
//
// Do not modify this file directly
////////////////////////////////////////////////////////////////////////////////

#include <algorithm>
#include <cstring>

#include "src/tint/ast/access.h"

namespace tint::ast {

/// ParseAccess parses a Access from a string.
/// @param str the string to parse
/// @returns the parsed enum, or Access::kUndefined if the string could not be parsed.
Access ParseAccess(std::string_view str) {
    std::array<uint64_t, 5> u64s = {};
    memcpy(u64s.data(), str.data(), str.size());

    if (u64s[0] == 0x0000000064616572) {
        return Access::kRead;
    }
    if (u64s[0] == 0x6972775f64616572) {
        if (u64s[1] == 0x0000000000006574) {
            return Access::kReadWrite;
        }
    }
    if (u64s[0] == 0x0000006574697277) {
        return Access::kWrite;
    }
    return Access::kUndefined;
}

std::ostream& operator<<(std::ostream& out, Access value) {
    switch (value) {
        case Access::kUndefined:
            return out << "undefined";
        case Access::kRead:
            return out << "read";
        case Access::kReadWrite:
            return out << "read_write";
        case Access::kWrite:
            return out << "write";
    }
    return out << "<unknown>";
}

}  // namespace tint::ast
