// Copyright 2020 The Tint Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

////////////////////////////////////////////////////////////////////////////////
// File generated by tools/src/cmd/gen
// using the template:
//   src/tint/ast/builtin_value.cc.tmpl
//
// Do not modify this file directly
////////////////////////////////////////////////////////////////////////////////

#include <algorithm>
#include <cstring>

#include "src/tint/ast/builtin_value.h"

namespace tint::ast {

/// ParseBuiltinValue parses a BuiltinValue from a string.
/// @param str the string to parse
/// @returns the parsed enum, or BuiltinValue::kInvalid if the string could not be parsed.
BuiltinValue ParseBuiltinValue(std::string_view str) {
    uint64_t word = 0u;
memcpy(&word, str.data(), std::min(str.size(), sizeof(word)));
    switch (((word * 537) % 83591) % 11) {
        case 0:
            if (str == "sample_index") {
                return BuiltinValue::kSampleIndex;
            }
            break;
        case 1:
            if (str == "workgroup_id") {
                return BuiltinValue::kWorkgroupId;
            }
            break;
        case 2:
            if (word == 0x6e695f6c61636f6c) {
                word = 0;
                str = str.substr(8);memcpy(&word, str.data(), std::min(str.size(), sizeof(word)));
    switch (((word * 1) % 83591) % 1) {
        case 0:
            if (word == 0x6e6f697461636f76) {
                word = 0;
                str = str.substr(8);memcpy(&word, str.data(), std::min(str.size(), sizeof(word)));
    switch (((word * 3) % 83591) % 2) {
        case 0:
            if (str == "_index") {
                return BuiltinValue::kLocalInvocationIndex;
            }
            break;
        case 1:
            if (str == "_id") {
                return BuiltinValue::kLocalInvocationId;
            }
            break;
    }
            }
            break;
    }
            }
            break;
        case 3:
            if (str == "vertex_index") {
                return BuiltinValue::kVertexIndex;
            }
            break;
        case 4:
            if (str == "global_invocation_id") {
                return BuiltinValue::kGlobalInvocationId;
            }
            break;
        case 5:
            if (str == "sample_mask") {
                return BuiltinValue::kSampleMask;
            }
            break;
        case 6:
            if (str == "num_workgroups") {
                return BuiltinValue::kNumWorkgroups;
            }
            break;
        case 7:
            if (str == "instance_index") {
                return BuiltinValue::kInstanceIndex;
            }
            break;
        case 8:
            if (str == "front_facing") {
                return BuiltinValue::kFrontFacing;
            }
            break;
        case 9:
            if (str == "frag_depth") {
                return BuiltinValue::kFragDepth;
            }
            break;
        case 10:
            if (str == "position") {
                return BuiltinValue::kPosition;
            }
            break;
    }
    return BuiltinValue::kInvalid;
}

std::ostream& operator<<(std::ostream& out, BuiltinValue value) {
    switch (value) {
        case BuiltinValue::kInvalid:
            return out << "invalid";
        case BuiltinValue::kPosition:
            return out << "position";
        case BuiltinValue::kVertexIndex:
            return out << "vertex_index";
        case BuiltinValue::kInstanceIndex:
            return out << "instance_index";
        case BuiltinValue::kFrontFacing:
            return out << "front_facing";
        case BuiltinValue::kFragDepth:
            return out << "frag_depth";
        case BuiltinValue::kLocalInvocationId:
            return out << "local_invocation_id";
        case BuiltinValue::kLocalInvocationIndex:
            return out << "local_invocation_index";
        case BuiltinValue::kGlobalInvocationId:
            return out << "global_invocation_id";
        case BuiltinValue::kWorkgroupId:
            return out << "workgroup_id";
        case BuiltinValue::kNumWorkgroups:
            return out << "num_workgroups";
        case BuiltinValue::kSampleIndex:
            return out << "sample_index";
        case BuiltinValue::kSampleMask:
            return out << "sample_mask";
        case BuiltinValue::kPointSize:
            return out << "point_size";
    }
    return out << "<unknown>";
}

}  // namespace tint::ast
