// Copyright 2023 The Tint Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

////////////////////////////////////////////////////////////////////////////////
// File generated by tools/src/cmd/gen
// using the template:
//   src/tint/ast/diagnostic_control.cc.tmpl
//
// Do not modify this file directly
////////////////////////////////////////////////////////////////////////////////

#include "src/tint/ast/diagnostic_control.h"

#include <string>

#include "src/tint/ast/identifier.h"
#include "src/tint/ast/templated_identifier.h"

namespace tint::ast {

DiagnosticControl::DiagnosticControl(type::DiagnosticSeverity sev, const Identifier* rule)
    : severity(sev), rule_name(rule) {
    TINT_ASSERT(AST, rule != nullptr);
    if (rule) {
        // It is invalid for a diagnostic rule name to be templated
        TINT_ASSERT(AST, !rule->Is<TemplatedIdentifier>());
    }
}

diag::Severity ToSeverity(type::DiagnosticSeverity sc) {
    switch (sc) {
        case type::DiagnosticSeverity::kError:
            return diag::Severity::Error;
        case type::DiagnosticSeverity::kWarning:
            return diag::Severity::Warning;
        case type::DiagnosticSeverity::kInfo:
            return diag::Severity::Note;
        default:
            return diag::Severity::InternalCompilerError;
    }
}

}  // namespace tint::ast
