// Copyright 2022 The Tint Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

////////////////////////////////////////////////////////////////////////////////
// File generated by tools/src/cmd/gen
// using the template:
//   src/tint/ast/texel_format.cc.tmpl
//
// Do not modify this file directly
////////////////////////////////////////////////////////////////////////////////

#include <algorithm>
#include <cstring>

#include "src/tint/ast/texel_format.h"

namespace tint::ast {

/// ParseTexelFormat parses a TexelFormat from a string.
/// @param str the string to parse
/// @returns the parsed enum, or TexelFormat::kInvalid if the string could not be parsed.
TexelFormat ParseTexelFormat(std::string_view str) {
    uint64_t u64 = 0u;
    memcpy(&u64, str.data(), std::min(str.size(), sizeof(u64)));
    switch (((u64 * 1028559) % 83591) % 16) {
        case 0:
            return (str == "rg32uint") ? TexelFormat::kRg32Uint : TexelFormat::kInvalid;
        case 1:
            return (str == "rgba32uint") ? TexelFormat::kRgba32Uint : TexelFormat::kInvalid;
        case 2:
            return (str == "r32sint") ? TexelFormat::kR32Sint : TexelFormat::kInvalid;
        case 3:
            return (str == "rgba16float") ? TexelFormat::kRgba16Float : TexelFormat::kInvalid;
        case 4:
            return (str == "rgba32sint") ? TexelFormat::kRgba32Sint : TexelFormat::kInvalid;
        case 5:
            return (str == "rgba16sint") ? TexelFormat::kRgba16Sint : TexelFormat::kInvalid;
        case 6:
            return (str == "rgba8unorm") ? TexelFormat::kRgba8Unorm : TexelFormat::kInvalid;
        case 7:
            return (str == "rgba16uint") ? TexelFormat::kRgba16Uint : TexelFormat::kInvalid;
        case 8:
            return (str == "r32float") ? TexelFormat::kR32Float : TexelFormat::kInvalid;
        case 9:
            return (str == "rgba8sint") ? TexelFormat::kRgba8Sint : TexelFormat::kInvalid;
        case 10:
            return (str == "r32uint") ? TexelFormat::kR32Uint : TexelFormat::kInvalid;
        case 11:
            return (str == "rg32sint") ? TexelFormat::kRg32Sint : TexelFormat::kInvalid;
        case 12:
            return (str == "rgba8snorm") ? TexelFormat::kRgba8Snorm : TexelFormat::kInvalid;
        case 13:
            return (str == "rgba32float") ? TexelFormat::kRgba32Float : TexelFormat::kInvalid;
        case 14:
            return (str == "rgba8uint") ? TexelFormat::kRgba8Uint : TexelFormat::kInvalid;
        case 15:
            return (str == "rg32float") ? TexelFormat::kRg32Float : TexelFormat::kInvalid;
    }
    return TexelFormat::kInvalid;
}

std::ostream& operator<<(std::ostream& out, TexelFormat value) {
    switch (value) {
        case TexelFormat::kInvalid:
            return out << "invalid";
        case TexelFormat::kRgba8Unorm:
            return out << "rgba8unorm";
        case TexelFormat::kRgba8Snorm:
            return out << "rgba8snorm";
        case TexelFormat::kRgba8Uint:
            return out << "rgba8uint";
        case TexelFormat::kRgba8Sint:
            return out << "rgba8sint";
        case TexelFormat::kRgba16Uint:
            return out << "rgba16uint";
        case TexelFormat::kRgba16Sint:
            return out << "rgba16sint";
        case TexelFormat::kRgba16Float:
            return out << "rgba16float";
        case TexelFormat::kR32Uint:
            return out << "r32uint";
        case TexelFormat::kR32Sint:
            return out << "r32sint";
        case TexelFormat::kR32Float:
            return out << "r32float";
        case TexelFormat::kRg32Uint:
            return out << "rg32uint";
        case TexelFormat::kRg32Sint:
            return out << "rg32sint";
        case TexelFormat::kRg32Float:
            return out << "rg32float";
        case TexelFormat::kRgba32Uint:
            return out << "rgba32uint";
        case TexelFormat::kRgba32Sint:
            return out << "rgba32sint";
        case TexelFormat::kRgba32Float:
            return out << "rgba32float";
    }
    return out << "<unknown>";
}

}  // namespace tint::ast
