# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


add_library(lib_tint_lang_wgsl_sem STATIC
  accessor_expression.cc
  accessor_expression.h
  array_count.cc
  array_count.h
  behavior.cc
  behavior.h
  block_statement.cc
  block_statement.h
  break_if_statement.cc
  break_if_statement.h
  builtin.cc
  builtin.h
  builtin_enum_expression.cc
  builtin_enum_expression.h
  call.cc
  call.h
  call_target.cc
  call_target.h
  evaluation_stage.h
  expression.cc
  expression.h
  external_texture.h
  for_loop_statement.cc
  for_loop_statement.h
  function.cc
  function.h
  function_expression.cc
  function_expression.h
  if_statement.cc
  if_statement.h
  index_accessor_expression.cc
  index_accessor_expression.h
  info.cc
  info.h
  load.cc
  load.h
  loop_statement.cc
  loop_statement.h
  materialize.cc
  materialize.h
  member_accessor_expression.cc
  member_accessor_expression.h
  module.cc
  module.h
  node.cc
  node.h
  parameter_usage.cc
  parameter_usage.h
  pipeline_stage_set.h
  sampler_texture_pair.h
  statement.cc
  statement.h
  struct.cc
  struct.h
  switch_statement.cc
  switch_statement.h
  type_expression.cc
  type_expression.h
  type_mappings.h
  value_constructor.cc
  value_constructor.h
  value_conversion.cc
  value_conversion.h
  value_expression.cc
  value_expression.h
  variable.cc
  variable.h
  while_statement.cc
  while_statement.h
)

target_link_libraries(lib_tint_lang_wgsl_sem
  lib_tint_lang_core_builtin
  lib_tint_lang_core_constant
  lib_tint_lang_core_type
  lib_tint_lang_wgsl_ast
  lib_tint_utils_containers
  lib_tint_utils_ice
  lib_tint_utils_math
  lib_tint_utils_rtti
  lib_tint_utils_symbol
  lib_tint_utils_text
  lib_tint_utils_traits
)

add_library(tint_lang_wgsl_sem:test STATIC
  builtin_test.cc
  diagnostic_severity_test.cc
  helper_test.h
  struct_test.cc
  value_expression_test.cc
)

target_link_libraries(tint_lang_wgsl_sem:test
  lib_tint_lang_core_type
  lib_tint_lang_wgsl_program
  lib_tint_lang_wgsl_resolver
  lib_tint_lang_wgsl_sem
)

