# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


tint_add_library(tint_lang_core_constant
  "lang/core/constant/clone_context.h"
  "lang/core/constant/composite.cc"
  "lang/core/constant/composite.h"
  "lang/core/constant/manager.cc"
  "lang/core/constant/manager.h"
  "lang/core/constant/node.cc"
  "lang/core/constant/node.h"
  "lang/core/constant/scalar.cc"
  "lang/core/constant/scalar.h"
  "lang/core/constant/splat.cc"
  "lang/core/constant/splat.h"
  "lang/core/constant/value.cc"
  "lang/core/constant/value.h"
)

tint_target_link_tint_libraries(tint_lang_core_constant
  tint_lang_core_builtin
  tint_lang_core_type
  tint_utils_containers
  tint_utils_math
  tint_utils_rtti
)

tint_target_sources(tint_unittests
  "lang/core/constant/composite_test.cc"
  "lang/core/constant/helper_test.h"
  "lang/core/constant/manager_test.cc"
  "lang/core/constant/scalar_test.cc"
  "lang/core/constant/splat_test.cc"
  "lang/core/constant/value_test.cc"
)

tint_target_link_tint_libraries(tint_unittests
  tint_lang_core_constant
  tint_lang_core_type
  tint_lang_wgsl_program
)

