# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################

include(lang/spirv/writer/ast_printer/BUILD.cmake)
include(lang/spirv/writer/common/BUILD.cmake)
include(lang/spirv/writer/printer/BUILD.cmake)

tint_add_library(tint_lang_spirv_writer
  "lang/spirv/writer/writer.cc"
  "lang/spirv/writer/writer.h"
)

tint_target_link_tint_libraries(tint_lang_spirv_writer
  tint_lang_spirv_writer_ast_printer
  tint_lang_spirv_writer_common
  tint_lang_spirv_writer_printer
  tint_lang_wgsl_reader_program_to_ir
)

tint_target_sources(tint_unittests
  "lang/spirv/writer/access_test.cc"
  "lang/spirv/writer/atomic_builtin_test.cc"
  "lang/spirv/writer/binary_test.cc"
  "lang/spirv/writer/bitcast_test.cc"
  "lang/spirv/writer/builtin_test.cc"
  "lang/spirv/writer/constant_test.cc"
  "lang/spirv/writer/construct_test.cc"
  "lang/spirv/writer/convert_test.cc"
  "lang/spirv/writer/discard_test.cc"
  "lang/spirv/writer/function_test.cc"
  "lang/spirv/writer/if_test.cc"
  "lang/spirv/writer/let_test.cc"
  "lang/spirv/writer/loop_test.cc"
  "lang/spirv/writer/switch_test.cc"
  "lang/spirv/writer/swizzle_test.cc"
  "lang/spirv/writer/texture_builtin_test.cc"
  "lang/spirv/writer/type_test.cc"
  "lang/spirv/writer/unary_test.cc"
  "lang/spirv/writer/var_test.cc"
  "lang/spirv/writer/writer_test.cc"
)

tint_target_link_tint_libraries(tint_unittests
  tint_lang_core_builtin
  tint_lang_core_ir
  tint_lang_core_type
)

tint_target_sources(tint_benchmark
  "lang/spirv/writer/writer_bench.cc"
)

tint_target_link_tint_libraries(tint_benchmark
  tint_bench
)

