# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################

include(lang/spirv/writer/ast_printer/BUILD.cmake)
include(lang/spirv/writer/common/BUILD.cmake)
include(lang/spirv/writer/printer/BUILD.cmake)

add_library(lib_tint_lang_spirv_writer STATIC
  writer.cc
  writer.h
)

target_link_libraries(lib_tint_lang_spirv_writer
  lib_tint_lang_spirv_writer_ast_printer
  lib_tint_lang_spirv_writer_common
  lib_tint_lang_spirv_writer_printer
  lib_tint_lang_wgsl_reader_program_to_ir
)

add_library(tint_lang_spirv_writer:test STATIC
  access_test.cc
  atomic_builtin_test.cc
  binary_test.cc
  bitcast_test.cc
  builtin_test.cc
  constant_test.cc
  construct_test.cc
  convert_test.cc
  discard_test.cc
  function_test.cc
  if_test.cc
  let_test.cc
  loop_test.cc
  switch_test.cc
  swizzle_test.cc
  texture_builtin_test.cc
  type_test.cc
  unary_test.cc
  var_test.cc
  writer_test.cc
)

target_link_libraries(tint_lang_spirv_writer:test
  lib_tint_lang_core_builtin
  lib_tint_lang_core_ir
  lib_tint_lang_core_type
  tint_lang_spirv_writer_common:test
)

