# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################

include(lang/spirv/writer/ast_printer/BUILD.cmake)
include(lang/spirv/writer/common/BUILD.cmake)
include(lang/spirv/writer/printer/BUILD.cmake)
include(lang/spirv/writer/raise/BUILD.cmake)

tint_add_target("lang/spirv/writer"
  lang/spirv/writer/output.h
  lang/spirv/writer/writer.cc
  lang/spirv/writer/writer.h
)

tint_target_add_dependencies("lang/spirv/writer"
  "utils/result"
)

if (TINT_BUILD_IR)
  tint_target_add_dependencies("lang/spirv/writer" "lang/core/ir/transform")
endif()

if (TINT_BUILD_SPV_WRITER)
  tint_target_add_dependencies("lang/spirv/writer" "lang/spirv/writer/ast_printer")
endif()

if (TINT_BUILD_SPV_WRITER)
  tint_target_add_dependencies("lang/spirv/writer" "lang/spirv/writer/common")
endif()

if (TINT_BUILD_SPV_WRITER  AND  TINT_BUILD_IR)
  tint_target_add_dependencies("lang/spirv/writer" "lang/spirv/writer/printer")
endif()

if (TINT_BUILD_SPV_WRITER  AND  TINT_BUILD_IR)
  tint_target_add_dependencies("lang/spirv/writer" "lang/spirv/writer/raise")
endif()

if (TINT_BUILD_IR)
  tint_target_add_dependencies("lang/spirv/writer" "lang/wgsl/reader/program_to_ir")
endif()

if (TINT_BUILD_SPV_READER  OR  TINT_BUILD_SPV_WRITER)
  tint_target_add_external_dependencies("lang/spirv/writer" "spirv-headers")
endif()

tint_add_target("lang/spirv/writer:test"
)

if (TINT_BUILD_IR)
  tint_target_add_sources("lang/spirv/writer:test" "lang/spirv/writer/access_test.cc")
endif()

if (TINT_BUILD_IR)
  tint_target_add_sources("lang/spirv/writer:test" "lang/spirv/writer/atomic_builtin_test.cc")
endif()

if (TINT_BUILD_IR)
  tint_target_add_sources("lang/spirv/writer:test" "lang/spirv/writer/binary_test.cc")
endif()

if (TINT_BUILD_IR)
  tint_target_add_sources("lang/spirv/writer:test" "lang/spirv/writer/bitcast_test.cc")
endif()

if (TINT_BUILD_IR)
  tint_target_add_sources("lang/spirv/writer:test" "lang/spirv/writer/builtin_test.cc")
endif()

if (TINT_BUILD_IR)
  tint_target_add_sources("lang/spirv/writer:test" "lang/spirv/writer/constant_test.cc")
endif()

if (TINT_BUILD_IR)
  tint_target_add_sources("lang/spirv/writer:test" "lang/spirv/writer/construct_test.cc")
endif()

if (TINT_BUILD_IR)
  tint_target_add_sources("lang/spirv/writer:test" "lang/spirv/writer/convert_test.cc")
endif()

if (TINT_BUILD_IR)
  tint_target_add_sources("lang/spirv/writer:test" "lang/spirv/writer/discard_test.cc")
endif()

if (TINT_BUILD_IR)
  tint_target_add_sources("lang/spirv/writer:test" "lang/spirv/writer/function_test.cc")
endif()

if (TINT_BUILD_IR)
  tint_target_add_sources("lang/spirv/writer:test" "lang/spirv/writer/if_test.cc")
endif()

if (TINT_BUILD_IR)
  tint_target_add_sources("lang/spirv/writer:test" "lang/spirv/writer/let_test.cc")
endif()

if (TINT_BUILD_IR)
  tint_target_add_sources("lang/spirv/writer:test" "lang/spirv/writer/loop_test.cc")
endif()

if (TINT_BUILD_IR)
  tint_target_add_sources("lang/spirv/writer:test" "lang/spirv/writer/switch_test.cc")
endif()

if (TINT_BUILD_IR)
  tint_target_add_sources("lang/spirv/writer:test" "lang/spirv/writer/swizzle_test.cc")
endif()

if (TINT_BUILD_IR)
  tint_target_add_sources("lang/spirv/writer:test" "lang/spirv/writer/texture_builtin_test.cc")
endif()

if (TINT_BUILD_IR)
  tint_target_add_sources("lang/spirv/writer:test" "lang/spirv/writer/type_test.cc")
endif()

if (TINT_BUILD_IR)
  tint_target_add_sources("lang/spirv/writer:test" "lang/spirv/writer/unary_test.cc")
endif()

if (TINT_BUILD_IR)
  tint_target_add_sources("lang/spirv/writer:test" "lang/spirv/writer/var_test.cc")
endif()

if (TINT_BUILD_IR)
  tint_target_add_sources("lang/spirv/writer:test" "lang/spirv/writer/writer_test.cc")
endif()

tint_target_add_dependencies("lang/spirv/writer:test"
  "lang/core"
  "lang/core/type"
)

if (TINT_BUILD_IR)
  tint_target_add_dependencies("lang/spirv/writer:test" "lang/core/ir")
endif()

if (TINT_BUILD_SPV_WRITER)
  tint_target_add_dependencies("lang/spirv/writer:test" "lang/spirv/writer/common:test")
endif()

tint_add_target("lang/spirv/writer:bench"
  lang/spirv/writer/writer_bench.cc
)

tint_target_add_dependencies("lang/spirv/writer:bench"
  "cmd/bench"
)

if (TINT_BUILD_SPV_WRITER)
  tint_target_add_dependencies("lang/spirv/writer:bench" "lang/spirv/writer")
endif()
