# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


add_library(lib_tint_lang_wgsl_resolver STATIC
  const_eval.cc
  const_eval.h
  ctor_conv_intrinsic.cc
  ctor_conv_intrinsic.h
  dependency_graph.cc
  dependency_graph.h
  intrinsic_table.cc
  intrinsic_table.h
  resolve.cc
  resolve.h
  resolver.cc
  resolver.h
  sem_helper.cc
  sem_helper.h
  uniformity.cc
  uniformity.h
  validator.cc
  validator.h
)

target_link_libraries(lib_tint_lang_wgsl_resolver
  lib_tint_lang_core_builtin
  lib_tint_lang_core_constant
  lib_tint_lang_core_type
  lib_tint_lang_wgsl_ast
  lib_tint_lang_wgsl_program
  lib_tint_lang_wgsl_sem
  lib_tint_utils_containers
  lib_tint_utils_diagnostic
  lib_tint_utils_macros
  lib_tint_utils_math
  lib_tint_utils_memory
  lib_tint_utils_result
  lib_tint_utils_rtti
  lib_tint_utils_text
)

add_library(tint_lang_wgsl_resolver:test STATIC
  address_space_layout_validation_test.cc
  address_space_validation_test.cc
  alias_analysis_test.cc
  array_accessor_test.cc
  assignment_validation_test.cc
  atomics_test.cc
  atomics_validation_test.cc
  attribute_validation_test.cc
  bitcast_validation_test.cc
  builtin_enum_test.cc
  builtin_structs_test.cc
  builtin_test.cc
  builtin_validation_test.cc
  builtins_validation_test.cc
  call_test.cc
  call_validation_test.cc
  compound_assignment_validation_test.cc
  compound_statement_test.cc
  const_assert_test.cc
  const_eval_binary_op_test.cc
  const_eval_bitcast_test.cc
  const_eval_builtin_test.cc
  const_eval_construction_test.cc
  const_eval_conversion_test.cc
  const_eval_indexing_test.cc
  const_eval_member_access_test.cc
  const_eval_runtime_semantics_test.cc
  const_eval_test.h
  const_eval_unary_op_test.cc
  control_block_validation_test.cc
  dependency_graph_test.cc
  diagnostic_control_test.cc
  dual_source_blending_extension_test.cc
  entry_point_validation_test.cc
  evaluation_stage_test.cc
  expression_kind_test.cc
  f16_extension_test.cc
  function_validation_test.cc
  host_shareable_validation_test.cc
  increment_decrement_validation_test.cc
  inferred_type_test.cc
  intrinsic_table_test.cc
  is_host_shareable_test.cc
  is_storeable_test.cc
  load_test.cc
  materialize_test.cc
  override_test.cc
  ptr_ref_test.cc
  ptr_ref_validation_test.cc
  resolver_behavior_test.cc
  resolver_helper_test.cc
  resolver_helper_test.h
  resolver_test.cc
  root_identifier_test.cc
  side_effects_test.cc
  struct_address_space_use_test.cc
  struct_layout_test.cc
  struct_pipeline_stage_use_test.cc
  type_validation_test.cc
  uniformity_test.cc
  unresolved_identifier_test.cc
  validation_test.cc
  validator_is_storeable_test.cc
  value_constructor_validation_test.cc
  variable_test.cc
  variable_validation_test.cc
)

target_link_libraries(tint_lang_wgsl_resolver:test
  lib_tint_lang_core_builtin
  lib_tint_lang_core_constant
  lib_tint_lang_core_type
  tint_lang_core_type:test
  lib_tint_lang_wgsl_ast
  lib_tint_lang_wgsl_ast_transform
  tint_lang_wgsl_ast:test
  lib_tint_lang_wgsl_program
  lib_tint_lang_wgsl_reader
  lib_tint_lang_wgsl_resolver
  lib_tint_lang_wgsl_sem
  tint_lang_wgsl_sem:test
  lib_tint_utils_containers
  lib_tint_utils_result
  lib_tint_utils_rtti
  lib_tint_utils_text
  lib_tint_utils_traits
)

