# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


add_library(lib_tint_lang_wgsl_resolver STATIC
  "lang/wgsl/resolver/const_eval.cc"
  "lang/wgsl/resolver/const_eval.h"
  "lang/wgsl/resolver/ctor_conv_intrinsic.cc"
  "lang/wgsl/resolver/ctor_conv_intrinsic.h"
  "lang/wgsl/resolver/dependency_graph.cc"
  "lang/wgsl/resolver/dependency_graph.h"
  "lang/wgsl/resolver/intrinsic_table.cc"
  "lang/wgsl/resolver/intrinsic_table.h"
  "lang/wgsl/resolver/resolve.cc"
  "lang/wgsl/resolver/resolve.h"
  "lang/wgsl/resolver/resolver.cc"
  "lang/wgsl/resolver/resolver.h"
  "lang/wgsl/resolver/sem_helper.cc"
  "lang/wgsl/resolver/sem_helper.h"
  "lang/wgsl/resolver/uniformity.cc"
  "lang/wgsl/resolver/uniformity.h"
  "lang/wgsl/resolver/validator.cc"
  "lang/wgsl/resolver/validator.h"
)

target_link_libraries(lib_tint_lang_wgsl_resolver
  lib_tint_lang_core_builtin
  lib_tint_lang_core_constant
  lib_tint_lang_core_type
  lib_tint_lang_wgsl_ast
  lib_tint_lang_wgsl_program
  lib_tint_lang_wgsl_sem
  lib_tint_utils_containers
  lib_tint_utils_diagnostic
  lib_tint_utils_macros
  lib_tint_utils_math
  lib_tint_utils_memory
  lib_tint_utils_result
  lib_tint_utils_rtti
  lib_tint_utils_text
)

tint_default_compile_options(lib_tint_lang_wgsl_resolver)

add_library(tint_lang_wgsl_resolver_test STATIC
  "lang/wgsl/resolver/address_space_layout_validation_test.cc"
  "lang/wgsl/resolver/address_space_validation_test.cc"
  "lang/wgsl/resolver/alias_analysis_test.cc"
  "lang/wgsl/resolver/array_accessor_test.cc"
  "lang/wgsl/resolver/assignment_validation_test.cc"
  "lang/wgsl/resolver/atomics_test.cc"
  "lang/wgsl/resolver/atomics_validation_test.cc"
  "lang/wgsl/resolver/attribute_validation_test.cc"
  "lang/wgsl/resolver/bitcast_validation_test.cc"
  "lang/wgsl/resolver/builtin_enum_test.cc"
  "lang/wgsl/resolver/builtin_structs_test.cc"
  "lang/wgsl/resolver/builtin_test.cc"
  "lang/wgsl/resolver/builtin_validation_test.cc"
  "lang/wgsl/resolver/builtins_validation_test.cc"
  "lang/wgsl/resolver/call_test.cc"
  "lang/wgsl/resolver/call_validation_test.cc"
  "lang/wgsl/resolver/compound_assignment_validation_test.cc"
  "lang/wgsl/resolver/compound_statement_test.cc"
  "lang/wgsl/resolver/const_assert_test.cc"
  "lang/wgsl/resolver/const_eval_binary_op_test.cc"
  "lang/wgsl/resolver/const_eval_bitcast_test.cc"
  "lang/wgsl/resolver/const_eval_builtin_test.cc"
  "lang/wgsl/resolver/const_eval_construction_test.cc"
  "lang/wgsl/resolver/const_eval_conversion_test.cc"
  "lang/wgsl/resolver/const_eval_indexing_test.cc"
  "lang/wgsl/resolver/const_eval_member_access_test.cc"
  "lang/wgsl/resolver/const_eval_runtime_semantics_test.cc"
  "lang/wgsl/resolver/const_eval_test.h"
  "lang/wgsl/resolver/const_eval_unary_op_test.cc"
  "lang/wgsl/resolver/control_block_validation_test.cc"
  "lang/wgsl/resolver/dependency_graph_test.cc"
  "lang/wgsl/resolver/diagnostic_control_test.cc"
  "lang/wgsl/resolver/dual_source_blending_extension_test.cc"
  "lang/wgsl/resolver/entry_point_validation_test.cc"
  "lang/wgsl/resolver/evaluation_stage_test.cc"
  "lang/wgsl/resolver/expression_kind_test.cc"
  "lang/wgsl/resolver/f16_extension_test.cc"
  "lang/wgsl/resolver/function_validation_test.cc"
  "lang/wgsl/resolver/host_shareable_validation_test.cc"
  "lang/wgsl/resolver/increment_decrement_validation_test.cc"
  "lang/wgsl/resolver/inferred_type_test.cc"
  "lang/wgsl/resolver/intrinsic_table_test.cc"
  "lang/wgsl/resolver/is_host_shareable_test.cc"
  "lang/wgsl/resolver/is_storeable_test.cc"
  "lang/wgsl/resolver/load_test.cc"
  "lang/wgsl/resolver/materialize_test.cc"
  "lang/wgsl/resolver/override_test.cc"
  "lang/wgsl/resolver/ptr_ref_test.cc"
  "lang/wgsl/resolver/ptr_ref_validation_test.cc"
  "lang/wgsl/resolver/resolver_behavior_test.cc"
  "lang/wgsl/resolver/resolver_helper_test.cc"
  "lang/wgsl/resolver/resolver_helper_test.h"
  "lang/wgsl/resolver/resolver_test.cc"
  "lang/wgsl/resolver/root_identifier_test.cc"
  "lang/wgsl/resolver/side_effects_test.cc"
  "lang/wgsl/resolver/struct_address_space_use_test.cc"
  "lang/wgsl/resolver/struct_layout_test.cc"
  "lang/wgsl/resolver/struct_pipeline_stage_use_test.cc"
  "lang/wgsl/resolver/type_validation_test.cc"
  "lang/wgsl/resolver/uniformity_test.cc"
  "lang/wgsl/resolver/unresolved_identifier_test.cc"
  "lang/wgsl/resolver/validation_test.cc"
  "lang/wgsl/resolver/validator_is_storeable_test.cc"
  "lang/wgsl/resolver/value_constructor_validation_test.cc"
  "lang/wgsl/resolver/variable_test.cc"
  "lang/wgsl/resolver/variable_validation_test.cc"
)

target_link_libraries(tint_lang_wgsl_resolver_test
  lib_tint_lang_core_builtin
  lib_tint_lang_core_constant
  lib_tint_lang_core_type
  tint_lang_core_type_test
  lib_tint_lang_wgsl_ast
  lib_tint_lang_wgsl_ast_transform
  tint_lang_wgsl_ast_test
  lib_tint_lang_wgsl_program
  lib_tint_lang_wgsl_reader
  lib_tint_lang_wgsl_resolver
  lib_tint_lang_wgsl_sem
  tint_lang_wgsl_sem_test
  lib_tint_utils_containers
  lib_tint_utils_result
  lib_tint_utils_rtti
  lib_tint_utils_text
  lib_tint_utils_traits
)

tint_default_compile_options(tint_lang_wgsl_resolver_test)

