# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


add_executable(tint_cmd_info_cmd
  "cmd/info/main.cc"
)

tint_target_link_tint_libraries(tint_cmd_info_cmd
  tint_cmd_common
  tint_lang_core_type
  tint_lang_wgsl_ast
  tint_lang_wgsl_inspector
  tint_utils_command
  tint_utils_containers
  tint_utils_text
)
tint_cmd_compile_options(tint_cmd_info_cmd)

