// Copyright 2021 The Tint Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

////////////////////////////////////////////////////////////////////////////////
// File generated by tools/intrinsic-gen
// using the template:
//   src/tint/resolver/constructable_type.cc.tmpl
// and the intrinsic defintion file:
//   src/tint/intrinsics.def
//
// Do not modify this file directly
////////////////////////////////////////////////////////////////////////////////

#include "src/tint/resolver/constructable_type.h"

namespace tint::resolver {

ConstructableType ParseConstructableType(const std::string& name) {
    if (name == "i32") {
        return ConstructableType::kI32;
    }
    if (name == "u32") {
        return ConstructableType::kU32;
    }
    if (name == "f32") {
        return ConstructableType::kF32;
    }
    if (name == "bool") {
        return ConstructableType::kBool;
    }
    if (name == "vec2") {
        return ConstructableType::kVec2;
    }
    if (name == "vec3") {
        return ConstructableType::kVec3;
    }
    if (name == "vec4") {
        return ConstructableType::kVec4;
    }
    if (name == "mat2x2") {
        return ConstructableType::kMat2x2;
    }
    if (name == "mat2x3") {
        return ConstructableType::kMat2x3;
    }
    if (name == "mat2x4") {
        return ConstructableType::kMat2x4;
    }
    if (name == "mat3x2") {
        return ConstructableType::kMat3x2;
    }
    if (name == "mat3x3") {
        return ConstructableType::kMat3x3;
    }
    if (name == "mat3x4") {
        return ConstructableType::kMat3x4;
    }
    if (name == "mat4x2") {
        return ConstructableType::kMat4x2;
    }
    if (name == "mat4x3") {
        return ConstructableType::kMat4x3;
    }
    if (name == "mat4x4") {
        return ConstructableType::kMat4x4;
    }
    return ConstructableType::kNone;
}

const char* str(ConstructableType i) {
    switch (i) {
        case ConstructableType::kNone:
            return "<none>";
        case ConstructableType::kI32:
            return "i32";
        case ConstructableType::kU32:
            return "u32";
        case ConstructableType::kF32:
            return "f32";
        case ConstructableType::kBool:
            return "bool";
        case ConstructableType::kVec2:
            return "vec2";
        case ConstructableType::kVec3:
            return "vec3";
        case ConstructableType::kVec4:
            return "vec4";
        case ConstructableType::kMat2x2:
            return "mat2x2";
        case ConstructableType::kMat2x3:
            return "mat2x3";
        case ConstructableType::kMat2x4:
            return "mat2x4";
        case ConstructableType::kMat3x2:
            return "mat3x2";
        case ConstructableType::kMat3x3:
            return "mat3x3";
        case ConstructableType::kMat3x4:
            return "mat3x4";
        case ConstructableType::kMat4x2:
            return "mat4x2";
        case ConstructableType::kMat4x3:
            return "mat4x3";
        case ConstructableType::kMat4x4:
            return "mat4x4";
    }
    return "<unknown>";
}

}  // namespace tint::resolver

