# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


add_library(lib_tint_utils_rtti STATIC
  "utils/rtti/castable.cc"
  "utils/rtti/castable.h"
  "utils/rtti/switch.h"
)

target_link_libraries(lib_tint_utils_rtti
  lib_tint_utils_macros
  lib_tint_utils_math
  lib_tint_utils_memory
  lib_tint_utils_traits
)

tint_default_compile_options(lib_tint_utils_rtti)

add_library(tint_utils_rtti_test STATIC
  "utils/rtti/castable_test.cc"
  "utils/rtti/switch_test.cc"
)

target_link_libraries(tint_utils_rtti_test
  lib_tint_utils_rtti
)

tint_default_compile_options(tint_utils_rtti_test)

