// Copyright 2019 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// DO NOT EDIT THIS FILE: This file is autogenerated

#ifndef SRC_DAWN_FUZZERS_DAWNLPMSERIALIZER_H_
#define SRC_DAWN_FUZZERS_DAWNLPMSERIALIZER_H_

#include "dawn/fuzzers/lpmfuzz/dawn_lpm.pb.h"
#include "dawn/wire/ChunkedCommandSerializer.h"

namespace dawn::wire {

void GetSerializedData(const fuzzing::Program& program,
                       dawn::wire::ChunkedCommandSerializer serializer);

}  // namespace dawn::wire

#endif  // SRC_DAWN_FUZZERS_DAWNLPMSERIALIZER_H_
