# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


add_library(lib_tint_utils_file STATIC
  "utils/file/tmpfile.h"
)
if ((NOT IS_LINUX)  AND  (NOT IS_MAC)  AND  (NOT IS_WIN))
  target_sources(lib_tint_utils_file PRIVATE
    "utils/file/tmpfile_other.cc"
  )
endif()
if (IS_LINUX  OR  IS_MAC)
  target_sources(lib_tint_utils_file PRIVATE
    "utils/file/tmpfile_posix.cc"
  )
endif()
if (IS_WIN)
  target_sources(lib_tint_utils_file PRIVATE
    "utils/file/tmpfile_windows.cc"
  )
endif()

target_link_libraries(lib_tint_utils_file
  lib_tint_utils_ice
  lib_tint_utils_text
)

tint_default_compile_options(lib_tint_utils_file)

add_library(tint_utils_file_test STATIC
  "utils/file/tmpfile_test.cc"
)

target_link_libraries(tint_utils_file_test
  lib_tint_utils_file
)

tint_default_compile_options(tint_utils_file_test)

