# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   /home/ben/src/dawn/tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################


add_library(lib_tint_utils_file STATIC
  tmpfile.h
)
if (!is_linux && !is_mac && !is_win)
  target_sources(lib_tint_utils_file
    $File.Name
  )
endif()
if (is_linux || is_mac)
  target_sources(lib_tint_utils_file
    $File.Name
  )
endif()
if (is_win)
  target_sources(lib_tint_utils_file
    $File.Name
  )
endif()

target_link_libraries(lib_tint_utils_file
  lib_tint_utils_ice
  lib_tint_utils_text
)

add_library(tint_utils_file:test STATIC
  tmpfile_test.cc
)

target_link_libraries(tint_utils_file:test
  lib_tint_utils_file
)

